const verites = [
  // TIER 0
  { text: "Quel est ton plus beau souvenir d’enfance ?", tier: 0, toz: 1 },
  { text: "Quel est ton film Disney préféré ?", tier: 0, toz: 1 },
  { text: "Quel est ton plat réconfort ultime ?", tier: 0, toz: 1 },
  { text: "Quelle est la chanson qui te rend toujours heureux·se ?", tier: 0, toz: 1 },
  { text: "Quel est le plus beau compliment qu’on t’ait fait ?", tier: 0, toz: 1 },
  { text: "Raconte une anecdote amusante qui t’est arrivée en vacances.", tier: 0, toz: 2 },
  { text: "Quel est ton talent caché que personne ne soupçonne ?", tier: 0, toz: 1 },
  { text: "Quelle est la dernière fois que tu as pleuré de rire ?", tier: 0, toz: 2 },
  { text: "Quel est l’objet que tu possèdes et auquel tu tiens le plus ?", tier: 0, toz: 1 },
  { text: "Si tu pouvais être un animal, lequel serais-tu et pourquoi ?", tier: 0, toz: 1 },
  { text: "Quel est ton endroit préféré dans ta ville ?", tier: 0, toz: 1 },
  { text: "Quel est le livre qui a changé ta vie ?", tier: 0, toz: 1 },
  { text: "Quelle est ta citation inspirante favorite ?", tier: 0, toz: 1 },
  { text: "Quel est ton jeu de société préféré ?", tier: 0, toz: 1 },
  { text: "Quelle est la chose la plus gentille que quelqu’un ait faite pour toi récemment ?", tier: 0, toz: 2 },
  { text: "Quel est ton rituel du matin idéal ?", tier: 0, toz: 1 },
  { text: "Quelle est la première chose que tu fais en rentrant chez toi ?", tier: 0, toz: 1 },
  { text: "Quel est ton souvenir le plus gênant mais maintenant tu en ris ?", tier: 0, toz: 2 },
  { text: "Quel est le métier dont tu rêvais quand tu étais petit·e ?", tier: 0, toz: 1 },
  { text: "Quelle est la plus belle preuve d’amitié qu’on t’ait donnée ?", tier: 0, toz: 1 },
  { text: "Quel est ton passe-temps favori que tu n’as jamais osé avouer ?", tier: 0, toz: 1 },
  { text: "Raconte-nous ton premier voyage inoubliable.", tier: 0, toz: 2 },
  { text: "Quelle est la chanson qui te fait pleurer à chaque fois ?", tier: 0, toz: 2 },
  { text: "Quel est ton plus grand rêve pour dans 10 ans ?", tier: 0, toz: 1 },
  { text: "Quelle est la personne qui t’inspire le plus dans ta vie ?", tier: 0, toz: 1 },
  { text: "Quel est ton péché mignon (nourriture) ?", tier: 0, toz: 1 },
  { text: "Quel est le premier disque que tu as acheté ?", tier: 0, toz: 1 },
  { text: "Quelle est la chose la plus étrange que tu aimes manger ?", tier: 0, toz: 1 },
  { text: "Raconte une blague qui te fait toujours rire.", tier: 0, toz: 1 },
  { text: "Quel est ton plus grand talent de karaoké ?", tier: 0, toz: 1 },
  { text: "Quel est le plus beau coucher de soleil que tu aies vu ?", tier: 0, toz: 1 },
  { text: "Quelle est ton odeur préférée ?", tier: 0, toz: 1 },
  { text: "Quelle est la dernière photo dans la galerie de ton téléphone ? (décris-la sans montrer)", tier: 0, toz: 2 },
  { text: "Quel est ton mot préféré ?", tier: 0, toz: 1 },
  { text: "Quel est le geste qui te fait te sentir aimé·e ?", tier: 0, toz: 1 },
  { text: "Quel est ton dessin animé préféré ?", tier: 0, toz: 1 },
  { text: "Quel est le plus beau cadeau que tu aies reçu ?", tier: 0, toz: 1 },
  { text: "Quelle est la première chose que tu regardes chez quelqu’un ?", tier: 0, toz: 1 },
  { text: "Quel est ton petit plaisir coupable de la vie quotidienne ?", tier: 0, toz: 1 },
  { text: "Raconte un moment embarrassant avec un professeur.", tier: 0, toz: 2 },
  { text: "Quel est le pays que tu aimerais visiter en premier ?", tier: 0, toz: 1 },
  { text: "Quelle est ta série télé à regarder en boucle ?", tier: 0, toz: 1 },
  { text: "Quel est ton animal de compagnie idéal ?", tier: 0, toz: 1 },
  { text: "Quelle est la chanson que tu chantes sous la douche ?", tier: 0, toz: 1 },
  { text: "Quel est ton rituel avant de dormir ?", tier: 0, toz: 1 },
  { text: "Quel est le jeu vidéo qui a marqué ton enfance ?", tier: 0, toz: 1 },
  { text: "Quelle est la plus longue distance que tu aies parcourue à pied ?", tier: 0, toz: 1 },
  { text: "Raconte un malentendu hilarant.", tier: 0, toz: 2 },
  { text: "Quel est ton dicton préféré ?", tier: 0, toz: 1 },
  { text: "Quel est le meilleur conseil qu’on t’ait donné ?", tier: 0, toz: 1 },
  { text: "Quel est ton bonbon préféré ?", tier: 0, toz: 1 },
  { text: "Quel est l’accessoire que tu mets toujours sur toi ?", tier: 0, toz: 1 },
  { text: "Quelle est la dernière appli que tu as installée ?", tier: 0, toz: 1 },
  { text: "Quel est ton chiffre porte-bonheur ?", tier: 0, toz: 1 },
  { text: "Raconte la première fois que tu as fait du vélo sans roulettes.", tier: 0, toz: 2 },
  { text: "Quelle est la couleur qui te va le mieux selon toi ?", tier: 0, toz: 1 },
  { text: "Quel est ton biscuit préféré avec le café ?", tier: 0, toz: 1 },
  { text: "Quel est le geste romantique que tu trouves le plus adorable ?", tier: 0, toz: 1 },
  { text: "Quel est ton dessert préféré quand tu es triste ?", tier: 0, toz: 1 },
  { text: "Qui était ton premier·e ami·e d’école ?", tier: 0, toz: 2 },
  { text: "Quelle est la chose la plus chère que tu aies achetée avec ton propre argent ?", tier: 0, toz: 2 },
  { text: "Quel est ton jeu de cartes préféré ?", tier: 0, toz: 1 },
  { text: "Quel est le plus beau compliment que tu puisses faire à un ami ?", tier: 0, toz: 1 },
  { text: "Quel est le film que tu as vu le plus de fois ?", tier: 0, toz: 1 },
  { text: "Quelle est la première chose que tu remarques dans une pièce ?", tier: 0, toz: 1 },
  { text: "Quel est le son le plus relaxant pour toi ?", tier: 0, toz: 1 },
  { text: "Quel est ton restaurant préféré et quel plat y commandes-tu toujours ?", tier: 0, toz: 2 },
  { text: "Quelle a été ta plus grosse peur quand tu étais enfant ?", tier: 0, toz: 2 },
  { text: "Qu’est-ce qui te fait sourire immédiatement ?", tier: 0, toz: 1 },
  { text: "Quel est ton vêtement doudou, celui dans lequel tu te sens bien ?", tier: 0, toz: 1 },
  { text: "Quel est le pire plat que tu aies cuisiné ?", tier: 0, toz: 2 },
  { text: "Quel est ton parfum de glace préféré ?", tier: 0, toz: 1 },
  { text: "Quel est le premier objet que tu sauverais d’un incendie ?", tier: 0, toz: 1 },
  { text: "Quel est ton karaoké du samedi soir ?", tier: 0, toz: 1 },
  { text: "Raconte une fois où tu as ri tellement fort que tu n’arrivais plus à respirer.", tier: 0, toz: 2 },
  { text: "Quel est le film le plus drôle que tu aies vu ?", tier: 0, toz: 1 },
  { text: "Quelle est la tenue dans laquelle tu te sens le plus beau/belle ?", tier: 0, toz: 1 },
  { text: "Quel est ton emoji le plus utilisé ?", tier: 0, toz: 1 },
  { text: "Quel est ton livre préféré ?", tier: 0, toz: 1 },
  { text: "Quel est ton cocktail sans alcool préféré ?", tier: 0, toz: 1 },
  { text: "Quelle est la chanson qui te donne envie de danser ?", tier: 0, toz: 1 },
  { text: "Quelle est la plus belle vue que tu aies admirée ?", tier: 0, toz: 1 },
  { text: "Quel est le plus long trajet en voiture que tu aies fait ?", tier: 0, toz: 1 },
  { text: "Quelle est ta fond d’ordinateur ou téléphone ?", tier: 0, toz: 1 },
  { text: "Quel est ton jeu de mots préféré ?", tier: 0, toz: 1 },
  { text: "Quel est ton album photo souvenir que tu aimes regarder ?", tier: 0, toz: 1 },
  { text: "Quelle est la matière scolaire que tu préférais ?", tier: 0, toz: 1 },
  { text: "Quel est l’objet le plus insolite que tu possèdes ?", tier: 0, toz: 2 },
  { text: "Quel est ton snack préféré pour une soirée film ?", tier: 0, toz: 1 },
  // TIER 1 (120 cartes)
  { text: "Quel a été ton premier baiser et comment était-ce ?", tier: 1, toz: 3 },
  { text: "Quel est ton crush secret au sein de ce groupe ?", tier: 1, toz: 4 },
  { text: "Quelle est la chose la plus romantique que tu aies faite ?", tier: 1, toz: 3 },
  { text: "Décris ton rendez-vous idéal.", tier: 1, toz: 2 },
  { text: "Quel est le compliment qui te fait le plus craquer ?", tier: 1, toz: 2 },
  { text: "Quel est ton principal défaut en couple ?", tier: 1, toz: 3 },
  { text: "Raconte ta première fois que tu as tenu la main de quelqu’un.", tier: 1, toz: 2 },
  { text: "Quel est ton langage de l’amour préféré ?", tier: 1, toz: 2 },
  { text: "Quel est le film le plus romantique selon toi ?", tier: 1, toz: 1 },
  { text: "Qu’est-ce qui te fait fondre chez une personne ?", tier: 1, toz: 2 },
  { text: "Quel est le pire rendez-vous que tu aies eu ?", tier: 1, toz: 3 },
  { text: "As-tu déjà écrit une lettre d’amour ? Si oui, à qui ?", tier: 1, toz: 3 },
  { text: "Quelle est la chanson qui te fait penser à ton ex ?", tier: 1, toz: 3 },
  { text: "Quel est ton plus grand turn-off chez un partenaire ?", tier: 1, toz: 2 },
  { text: "Quel est le vêtement que tu trouves le plus sexy sur les autres ?", tier: 1, toz: 2 },
  { text: "Raconte un mensonge que tu as dit par amour.", tier: 1, toz: 3 },
  { text: "Quel est ton fantasme romantique inavoué ?", tier: 1, toz: 4 },
  { text: "Qui dans ce groupe est la personne la plus attirante selon toi ?", tier: 1, toz: 4 },
  { text: "As-tu déjà eu un coup de foudre ? Où et quand ?", tier: 1, toz: 2 },
  { text: "Quel est ton souvenir le plus gênant lors d’un date ?", tier: 1, toz: 3 },
  { text: "Quel est le geste tendre que tu aimerais recevoir là maintenant ?", tier: 1, toz: 2 },
  { text: "As-tu déjà embrassé plusieurs personnes le même jour ?", tier: 1, toz: 3 },
  { text: "Quel est ton plus grand caprice en amour ?", tier: 1, toz: 2 },
  { text: "As-tu déjà utilisé une appli de rencontre ? Laquelle ?", tier: 1, toz: 2 },
  { text: "Quel est le message le plus osé que tu aies envoyé ?", tier: 1, toz: 4 },
  { text: "Quel est le plus gros secret que tu as caché à un·e partenaire ?", tier: 1, toz: 4 },
  { text: "Raconte ton premier slow ou danse collée.", tier: 1, toz: 2 },
  { text: "Qui a été ton premier amour secret d’école ?", tier: 1, toz: 3 },
  { text: "Quel est ton pire défaut en drague ?", tier: 1, toz: 2 },
  { text: "As-tu déjà fait le premier pas ? Raconte.", tier: 1, toz: 3 },
  { text: "Quel est le relooking qui t’a fait le plus d’effet chez un·e ami·e ?", tier: 1, toz: 1 },
  { text: "Quel est ton mot le plus romantique que tu oses dire ?", tier: 1, toz: 2 },
  { text: "Quelle est la chanson que tu aimerais dédier à quelqu’un ici ?", tier: 1, toz: 3 },
  { text: "Quel est ton type physique idéal (cheveux, yeux, carrure) ?", tier: 1, toz: 2 },
  { text: "As-tu déjà été jaloux·se sans raison ?", tier: 1, toz: 3 },
  { text: "Quel est le cadeau le plus romantique que tu aies offert ?", tier: 1, toz: 2 },
  { text: "Raconte une fois où tu as mal interprété un signe amoureux.", tier: 1, toz: 3 },
  { text: "Quel est le pays qui te fait le plus rêver pour une lune de miel ?", tier: 1, toz: 1 },
  { text: "As-tu déjà flirté en ligne avec un inconnu ?", tier: 1, toz: 3 },
  { text: "Quel est le trait de caractère qui te fait craquer instantanément ?", tier: 1, toz: 1 },
  { text: "Qui est ton crush célèbre ?", tier: 1, toz: 2 },
  { text: "As-tu déjà eu une relation interdite ?", tier: 1, toz: 4 },
  { text: "Quel est le pire mot que tu aies utilisé pour draguer ?", tier: 1, toz: 3 },
  { text: "Quelle est ta technique infaillible pour attirer l’attention de quelqu’un ?", tier: 1, toz: 2 },
  { text: "As-tu déjà envoyé un nude par inadvertance ?", tier: 1, toz: 5 },
  { text: "Quel est le surnom que tu donnerais à ton·ta petit·e ami·e ?", tier: 1, toz: 1 },
  { text: "Raconte une fois où tu as été largué·e de façon humiliante.", tier: 1, toz: 4 },
  { text: "Quel est le vêtement le plus sexy que tu possèdes ?", tier: 1, toz: 3 },
  { text: "Qui a été ton premier date ?", tier: 1, toz: 2 },
  { text: "Quel est le signe astrologique qui t’attire le moins ?", tier: 1, toz: 1 },
  { text: "Quelle est la chose la plus embarrassante que ton crush t’ait vue faire ?", tier: 1, toz: 4 },
  { text: "As-tu déjà menti sur ton âge pour plaire ?", tier: 1, toz: 3 },
  { text: "Quel est le premier film romantique que tu as vu ?", tier: 1, toz: 1 },
  { text: "Quelle est la chanson que tu voudrais qu’on te chante ?", tier: 1, toz: 2 },
  { text: "As-tu déjà eu un coup de foudre dans un transport en commun ?", tier: 1, toz: 2 },
  { text: "Quel est le meilleur geste de tendresse selon toi ?", tier: 1, toz: 1 },
  { text: "Quel est le message que tu aimerais recevoir maintenant ?", tier: 1, toz: 2 },
  { text: "As-tu déjà dragué un serveur/serveuse ?", tier: 1, toz: 3 },
  { text: "Quel est ton fantasme romantique le plus soft ?", tier: 1, toz: 2 },
  { text: "Qui est la personne la plus romantique que tu connaisses ?", tier: 1, toz: 1 },
  { text: "Quel est le plus beau souvenir de slow que tu aies ?", tier: 1, toz: 2 },
  { text: "As-tu déjà offert des fleurs spontanément ? À qui ?", tier: 1, toz: 2 },
  { text: "Quel est le mot doux que tu aimerais entendre ?", tier: 1, toz: 1 },
  { text: "Quel est ton pire date raconté en trois mots ?", tier: 1, toz: 3 },
  { text: "Raconte la fois où tu as osé aborder quelqu’un.", tier: 1, toz: 3 },
  // TIER 2 (100 cartes)
  { text: "Quel est le lieu le plus insolite où tu as eu une relation ?", tier: 2, toz: 5 },
  { text: "Quel a été ton moment le plus embarrassant au lit ?", tier: 2, toz: 5 },
  { text: "As-tu déjà simulé un orgasme ?", tier: 2, toz: 5 },
  { text: "Quelle est la chose la plus coquine que tu aies dite à haute voix ?", tier: 2, toz: 4 },
  { text: "Quel est le film érotique que tu as le plus apprécié ?", tier: 2, toz: 4 },
  { text: "As-tu déjà envoyé un message cochon pendant une réunion ?", tier: 2, toz: 5 },
  { text: "Quelle est la partie de ton corps que tu préfères qu’on touche ?", tier: 2, toz: 4 },
  { text: "Quel est ton plus grand turn-on (ce qui t’excite le plus) ?", tier: 2, toz: 4 },
  { text: "As-tu déjà fait l’amour dans une voiture ?", tier: 2, toz: 5 },
  { text: "Quel est le jouet intime que tu aimerais essayer ?", tier: 2, toz: 5 },
  { text: "As-tu déjà eu une relation d’un soir sans lendemain ?", tier: 2, toz: 5 },
  { text: "Quel est le vêtement que tu trouves le plus excitant à enlever ?", tier: 2, toz: 4 },
  { text: "Quelle est la chose la plus sale que tu aies murmurée à l’oreille ?", tier: 2, toz: 5 },
  { text: "Quel est ton fantasme impliquant une personne du même sexe ?", tier: 2, toz: 5 },
  { text: "As-tu déjà utilisé de la nourriture au lit ?", tier: 2, toz: 5 },
  { text: "Quel est le rêve érotique le plus marquant que tu aies fait ?", tier: 2, toz: 5 },
  { text: "As-tu déjà fait un striptease amateur ? Pour qui ?", tier: 2, toz: 5 },
  { text: "Quelle est la position sexuelle que tu préfères ?", tier: 2, toz: 5 },
  { text: "As-tu déjà eu un orgasme sans pénétration ?", tier: 2, toz: 5 },
  { text: "Quel est le surnom coquin que tu as donné à ton/ta partenaire ?", tier: 2, toz: 4 },
  { text: "Quelle est la chanson que tu mets pour une ambiance sensuelle ?", tier: 2, toz: 3 },
  { text: "As-tu déjà pratiqué le massage érotique ?", tier: 2, toz: 5 },
  { text: "Quel est le sextoy que tu as déjà utilisé ?", tier: 2, toz: 5 },
  { text: "As-tu déjà eu une relation avec un·e ami·e proche ?", tier: 2, toz: 5 },
  { text: "Quel est le plus long rapport sexuel que tu aies eu ?", tier: 2, toz: 5 },
  { text: "As-tu déjà été surpris·e en pleine action ?", tier: 2, toz: 6 },
  { text: "Quelle est l’expérience la plus osée que tu aies faite en public ?", tier: 2, toz: 6 },
  { text: "As-tu déjà participé à un jeu sensuel (Action ou Vérité, strip…) ?", tier: 2, toz: 5 },
  { text: "Quel est le baiser le plus chaud que tu aies reçu ?", tier: 2, toz: 4 },
  { text: "Quelle est la partie du corps que tu aimes le plus caresser chez l’autre ?", tier: 2, toz: 4 },
  { text: "As-tu déjà offert un sous-vêtement sexy ?", tier: 2, toz: 4 },
  { text: "Quel est le mot coquin qui te fait le plus réagir ?", tier: 2, toz: 4 },
  { text: "As-tu déjà eu une relation pendant tes règles ?", tier: 2, toz: 5 },
  { text: "Quel est le pire compliment qu’on t’ait fait au lit ?", tier: 2, toz: 4 },
  { text: "As-tu déjà laissé une marque (suçon) visible volontairement ?", tier: 2, toz: 5 },
  { text: "Quelle est ta limite douce que tu aimerais repousser ?", tier: 2, toz: 5 },
  { text: "As-tu déjà joué à la bouteille avec de vrais gages ?", tier: 2, toz: 4 },
  { text: "Quel est ton fantasme de jeux de rôle ?", tier: 2, toz: 5 },
  { text: "Quelle est la chose la plus exhibitionniste que tu aies faite ?", tier: 2, toz: 6 },
  { text: "As-tu déjà utilisé un miroir pendant l’acte ?", tier: 2, toz: 5 },
  { text: "Quel est le nombre de partenaires que tu as eus ?", tier: 2, toz: 6 },
  // TIER 3 (80 cartes)
  { text: "Quel est le détail le plus intime que tu connais sur {Joueur} ?", tier: 3, toz: 6 },
  { text: "Raconte la dernière fois que tu t’es masturbé·e (lieu et pensée).", tier: 3, toz: 7 },
  { text: "As-tu déjà fait l’amour dans un lieu public en journée ?", tier: 3, toz: 7 },
  { text: "Quel est le moment le plus salace que tu as vécu à une soirée ?", tier: 3, toz: 7 },
  { text: "Montre le dernier contenu coquin que tu as reçu.", tier: 3, toz: 7 },
  { text: "As-tu déjà eu une relation à trois ?", tier: 3, toz: 8 },
  { text: "Quel est le rôle que tu préfères : dominant·e ou soumis·e ?", tier: 3, toz: 7 },
  { text: "Quel est le geste le plus cochon que tu aies fait dans une piscine ?", tier: 3, toz: 7 },
  { text: "As-tu déjà filmé un moment intime ?", tier: 3, toz: 8 },
  { text: "Quel est le bruit le plus embarrassant que tu as fait au lit ?", tier: 3, toz: 7 },
  { text: "As-tu déjà utilisé de la glace ou de la cire pendant un rapport ?", tier: 3, toz: 7 },
  { text: "Quelle est la tenue sex la plus provocante que tu aies portée ?", tier: 3, toz: 6 },
  { text: "As-tu déjà eu un orgasme dans un endroit insolite ?", tier: 3, toz: 7 },
  { text: "Quel est le scénario X que tu aimerais réaliser ?", tier: 3, toz: 8 },
  { text: "As-tu déjà échangé de partenaires ?", tier: 3, toz: 8 },
  { text: "Quel est le compliment le plus cochon qu’on t’ait fait ?", tier: 3, toz: 6 },
  { text: "As-tu déjà eu une relation en étant attaché·e ?", tier: 3, toz: 7 },
  { text: "Quelle est la pratique que tu aimerais essayer avec {Joueur} ?", tier: 3, toz: 8 },
  { text: "As-tu déjà fait du BDSM soft ?", tier: 3, toz: 7 },
  { text: "Quel est le jouet le plus coquin que tu caches ?", tier: 3, toz: 7 },
  { text: "As-tu déjà eu une relation sous la douche avec quelqu’un que tu découvrais à peine ?", tier: 3, toz: 7 },
  { text: "Quel est le pire plan cul que tu aies eu ?", tier: 3, toz: 7 },
  { text: "As-tu déjà porté un plug en public ?", tier: 3, toz: 8 },
  { text: "Quelle est la partie de ton anatomie que tu aimes le moins et pourquoi ?", tier: 3, toz: 6 },
  { text: "As-tu déjà donné un faux espoir à quelqu’un pour un rapport ?", tier: 3, toz: 6 },
  { text: "Quel est le sexto le plus chaud que tu aies écrit ?", tier: 3, toz: 7 },
  { text: "As-tu déjà eu une relation avec un·e inconnu·e rencontré·e le soir même ?", tier: 3, toz: 7 },
  // TIER 4 (70 cartes)
  { text: "Décris en détail le préliminaire le plus intense que tu aies donné.", tier: 4, toz: 9 },
  { text: "Quelle est la taille maximale de ce que tu as pénétré ou qui t’a pénétré·e ? (en centimètres)", tier: 4, toz: 9 },
  { text: "As-tu déjà fait un 69 ? Avec qui ?", tier: 4, toz: 9 },
  { text: "Quel est le liquide corporel que tu as déjà reçu ou donné ?", tier: 4, toz: 9 },
  { text: "As-tu déjà léché des parties intimes dans un endroit semi-public ?", tier: 4, toz: 10 },
  { text: "Quel est le plus grand objet que tu aies utilisé pour ton plaisir ?", tier: 4, toz: 9 },
  { text: "As-tu déjà pratiqué l’anulingus ?", tier: 4, toz: 10 },
  { text: "Quelle est la pratique sexuelle la plus extrême que tu aies expérimentée ?", tier: 4, toz: 10 },
  { text: "As-tu déjà porté un gode ceinture ou en as reçu ?", tier: 4, toz: 10 },
  { text: "Montre les marques que tu as faites ou reçues (si visibles).", tier: 4, toz: 10 },
  { text: "As-tu déjà pratiqué le fisting ?", tier: 4, toz: 10 },
  { text: "Quel est le plus grand nombre d’orgasmes que tu aies eu en une seule fois ?", tier: 4, toz: 9 },
  { text: "As-tu déjà goûté ton propre sperme ou cyprine ?", tier: 4, toz: 10 },
  { text: "Quelle est la chose la plus dégradante que tu aies acceptée au lit ?", tier: 4, toz: 10 },
  { text: "As-tu déjà eu une relation en échangeant des fluides avec un·e inconnu·e ?", tier: 4, toz: 10 },
  { text: "Quel est le défi sexuel le plus osé que tu aies relevé ?", tier: 4, toz: 10 },
  { text: "Parmi les joueurs autour de toi, avec qui accepterais-tu une nuit torride ?", tier: 4, toz: 10 },
  { text: "As-tu déjà participé à un gang bang ?", tier: 4, toz: 10 },
  { text: "Quel est le lubrifiant que tu préfères ? (marque ou type)", tier: 4, toz: 9 },
  { text: "As-tu déjà mis un sextoy dans un endroit imprévu ?", tier: 4, toz: 9 },
  { text: "Est-ce que tu t’es déjà rasé·e intégralement pour une occasion ?", tier: 4, toz: 8 },
  { text: "Quel est le pire plan B que tu aies eu à cause d’un rapport ?", tier: 4, toz: 9 },
  { text: "As-tu déjà utilisé un plug télécommandé en public avec quelqu’un ?", tier: 4, toz: 10 },
  { text: "Quelle est la partouze à laquelle tu as participé ?", tier: 4, toz: 10 },
  { text: "Décris ta plus grande zone érogène en termes crus.", tier: 4, toz: 9 },
  { text: "As-tu déjà eu une relation avec une personne pendant que quelqu’un regardait ?", tier: 4, toz: 10 },
  { text: "Quel est le plus gros sextoy de ta collection ?", tier: 4, toz: 9 },
  { text: "As-tu déjà reçu un cumshot sur le visage ?", tier: 4, toz: 10 },
  { text: "Quel est ton pire accident de digestion pendant l’acte ?", tier: 4, toz: 10 },
  { text: "As-tu déjà fait l’amour avec une personne de plus de 20 ans d’écart ?", tier: 4, toz: 9 },
];
const actions = [
  // ---------- TIER 0 (130 actions) ----------
  { text: "Fais un câlin de 10 secondes à la personne à ta droite.", tier: 0, toz: 1 },
  { text: "Imite un animal choisi par le groupe pendant 20 secondes.", tier: 0, toz: 2 },
  { text: "Danse la Macarena pendant 30 secondes.", tier: 0, toz: 2 },
  { text: "Offre un verre à {Joueur} avec un baiser sur la main.", tier: 0, toz: 2 },
  { text: "Fais 10 pompes en criant « Je suis une star » entre chaque.", tier: 0, toz: 2 },
  { text: "Chante le refrain de ta chanson préférée avec émotion.", tier: 0, toz: 1 },
  { text: "Porte {Joueur} sur ton dos et fais le tour de la pièce.", tier: 0, toz: 3 },
  { text: "Fais une déclaration d’amitié à chaque joueur.", tier: 0, toz: 2 },
  { text: "Mime un objet loufoque et les autres doivent deviner.", tier: 0, toz: 1 },
  { text: "Fais un compliment personnalisé à chaque personne présente.", tier: 0, toz: 2 },
  { text: "Raconte une histoire drôle en remplaçant les noms par des noms de fruits.", tier: 0, toz: 2 },
  { text: "Chuchote un mot doux à l’oreille de {Joueur}.", tier: 0, toz: 1 },
  { text: "Ferme les yeux et laisse-toi guider par le groupe pendant 2 minutes.", tier: 0, toz: 3 },
  { text: "Fais une pyramide humaine avec les autres (si possible).", tier: 0, toz: 4 },
  { text: "Écris un petit mot gentil sur le front de {Joueur}.", tier: 0, toz: 1 },
  { text: "Raconte une blague en imitant l’accent imposé par {Joueur}.", tier: 0, toz: 2 },
  { text: "Fais le tour de table en sautillant.", tier: 0, toz: 2 },
  { text: "Donne un surnom rigolo à chaque joueur.", tier: 0, toz: 1 },
  { text: "Fais une bataille de pouce avec tout le monde (et perds exprès).", tier: 0, toz: 1 },
  { text: "Gratte le dos de {Joueur} pendant 30 secondes.", tier: 0, toz: 1 },
  { text: "Fais une ronde joyeuse en chantant « Joyeux anniversaire » même si ce n’est pas le cas.", tier: 0, toz: 2 },
  { text: "Montre ta plus belle grimace selfie.", tier: 0, toz: 1 },
  { text: "Fais un massage des épaules à {Joueur} pendant 1 minute.", tier: 0, toz: 1 },
  { text: "Chante une berceuse en voix de fausset.", tier: 0, toz: 2 },
  { text: "Fais une sculpture avec tout ce que tu trouves sur la table.", tier: 0, toz: 2 },
  { text: "Porte un toast avec un discours inspirant.", tier: 0, toz: 2 },
  { text: "Fixe {Joueur} dans les yeux sans rigoler pendant 30 secondes.", tier: 0, toz: 3 },
  { text: "Fais une démonstration de yoga (même approximative).", tier: 0, toz: 2 },
  { text: "Raconte une histoire effrayante en allumant une lampe torche sous ton menton.", tier: 0, toz: 2 },
  { text: "Fais un concours de chuchotements : le groupe doit répéter ta phrase.", tier: 0, toz: 1 },
  { text: "Donne un bonbon à chaque joueur sans utiliser tes mains.", tier: 0, toz: 2 },
  { text: "Fais une pyramide de cartes avec au moins 5 étages (sans tricher).", tier: 0, toz: 3 },
  { text: "Exécute une chorégraphie TikTok simple devant tout le monde.", tier: 0, toz: 2 },
  { text: "Récite un poème d’amour improvisé dédié à ton verre.", tier: 0, toz: 1 },
  { text: "Fais deviner un animal en le mimant seulement avec les sons.", tier: 0, toz: 1 },
  { text: "Trouve une ressemblance entre chaque joueur et un objet de la pièce.", tier: 0, toz: 1 },
  { text: "Fais un avion en papier et offre-le à {Joueur} avec un mot doux.", tier: 0, toz: 1 },
  { text: "Invente un cri de guerre pour le groupe et fais-le répéter.", tier: 0, toz: 2 },
  { text: "Fais le tour de la pièce en marchant à quatre pattes.", tier: 0, toz: 2 },
  { text: "Improvise une séance de méditation guidée absurde.", tier: 0, toz: 2 },
  { text: "Porte les chaussettes de {Joueur} au-dessus de tes propres chaussures pendant 10 minutes.", tier: 0, toz: 2 },
  { text: "Fais une imitation de ton personnage de dessin animé préféré.", tier: 0, toz: 1 },
  { text: "Chante une chanson en yaourt (langue inventée) et les autres doivent deviner le titre.", tier: 0, toz: 2 },
  { text: "Fais la brouette avec l’aide de {Joueur} pendant 10 mètres.", tier: 0, toz: 3 },
  { text: "Mime un slow très très lent en portant un coussin.", tier: 0, toz: 1 },
  { text: "Essaie de faire rire {Joueur} en moins de 30 secondes uniquement avec des grimaces.", tier: 0, toz: 2 },
  { text: "Décris une couleur sans utiliser son nom, les autres doivent deviner.", tier: 0, toz: 1 },
  { text: "Fais un compliment inversé (un peu moqueur) à {Joueur} puis un vrai compliment.", tier: 0, toz: 1 },
  { text: "Danse une valse avec un balai pendant 30 secondes.", tier: 0, toz: 2 },
  { text: "Appelle un faux correspondant et tiens une conversation sérieuse de 1 minute sur un sujet absurde.", tier: 0, toz: 3 },
  { text: "Exécute le mouvement le plus exagéré possible quand tu as besoin d'aller aux toilettes.", tier: 0, toz: 1 },
  { text: "Invente une petite chanson pour {Joueur} en utilisant son prénom au moins 5 fois.", tier: 0, toz: 1 },
  { text: "Cache un objet dans la pièce et guide le groupe avec des sons chaud/froid.", tier: 0, toz: 2 },
  { text: "Fais un selfie idiot avec tous les joueurs et impose le filtre le plus ridicule.", tier: 0, toz: 1 },
  { text: "Exprime une émotion dictée par le groupe (joie, tristesse, colère, etc.) de manière exagérée.", tier: 0, toz: 1 },
  { text: "Joue un air de musique avec ta bouche (beatbox ou sifflement) pendant 20 secondes.", tier: 0, toz: 1 },
  { text: "Trouve 3 points communs bizarres entre toi et {Joueur}.", tier: 0, toz: 1 },
  { text: "Fais le tour du salon en pas chassés.", tier: 0, toz: 2 },
  { text: "Transforme-toi en statue pendant 1 minute, les autres peuvent te faire rire.", tier: 0, toz: 2 },
  { text: "Raconte une histoire en ne parlant qu'avec des voyelles.", tier: 0, toz: 2 },
  { text: "Fais un check (fist bump) à tout le monde avec un petit commentaire sympa.", tier: 0, toz: 1 },
  { text: "Montre ton meilleur dab.", tier: 0, toz: 1 },
  { text: "Fais deviner un film en n'utilisant que des gestes interdits de pointer.", tier: 0, toz: 2 },
  { text: "Imite le rire de {Joueur} le plus fidèlement possible.", tier: 0, toz: 1 },
  { text: "Fais un bruit d'animal en chœur avec le voisin de droite.", tier: 0, toz: 1 },
  { text: "Invente un super-héros avec le nom de {Joueur} et décris ses pouvoirs.", tier: 0, toz: 1 },
  { text: "Fais un vœu à voix haute pour le reste de la soirée.", tier: 0, toz: 1 },
  { text: "Ferme les yeux et identifie les voix des autres sans te tromper.", tier: 0, toz: 2 },
  { text: "Donne une leçon de drague d'une discipline imaginaire.", tier: 0, toz: 2 },
  { text: "Mets le bazar dans tes cheveux puis refais ta coiffure en 30 secondes.", tier: 0, toz: 1 },
  { text: "Fais le tour des joueurs en leur offrant un mot doux écrit sur un coin de serviette.", tier: 0, toz: 1 },
  { text: "Invente une langue fictive et tiens une conversation avec toi-même dedans.", tier: 0, toz: 2 },

  // ---------- TIER 1 (120 actions – flirt doux, rapprochements, gages un peu plus osés) ----------
  { text: "Donne un baiser sur la joue à {Joueur} et dis-lui « Tu es magnifique ce soir ».", tier: 1, toz: 3 },
  { text: "Fais un slow langoureux avec l’élu·e de ton choix sur une chanson romantique.", tier: 1, toz: 3 },
  { text: "Mange un morceau de fruit dans la bouche de {Joueur} (sans les mains).", tier: 1, toz: 4 },
  { text: "Fais un massage des mains à {Joueur} en le/la regardant dans les yeux.", tier: 1, toz: 3 },
  { text: "Chuchote un secret coquin à l’oreille de {Joueur}.", tier: 1, toz: 4 },
  { text: "Prends la pose la plus séduisante de ta vie et demande aux autres de te noter.", tier: 1, toz: 2 },
  { text: "Fais un bras de fer sensuel avec {Joueur} (rapprochement maximum).", tier: 1, toz: 3 },
  { text: "Danse une salsa improvisée avec {Joueur} (même s'il n'y a pas de musique).", tier: 1, toz: 3 },
  { text: "Offre un sous-vêtement (fictif) comme si c'était un cadeau de Noël à {Joueur}.", tier: 1, toz: 3 },
  { text: "Fais un câlin de 20 secondes à {Joueur} en disant que c'est « pour la science ».", tier: 1, toz: 2 },
  { text: "Écris un mot sensuel sur le dos de {Joueur} avec ton doigt, il/elle doit deviner le mot.", tier: 1, toz: 4 },
  { text: "Simule une situation de drague dans un bar avec {Joueur}, avec accent si tu veux.", tier: 1, toz: 3 },
  { text: "Fais une déclaration d'amour théâtrale à un objet choisi par le groupe.", tier: 1, toz: 2 },
  { text: "Prends la main de {Joueur} et promène-toi en parlant comme si vous étiez dans un film romantique.", tier: 1, toz: 2 },
  { text: "Donne un baiser sur la main de {Joueur} à genoux.", tier: 1, toz: 3 },
  { text: "Fais un massage du cou à {Joueur} en fredonnant une chanson sensuelle.", tier: 1, toz: 3 },
  { text: "Joue au jeu de la carte (tu tires une carte, si c'est rouge tu embrasses la main, si noire la joue).", tier: 1, toz: 2 },
  { text: "Enlace {Joueur} par derrière et pose ton menton sur son épaule pendant 15 secondes.", tier: 1, toz: 3 },
  { text: "Invente un slow torride sur une musique inventée par le groupe.", tier: 1, toz: 3 },
  { text: "Chuchote « tu as de beaux yeux tu sais » à {Joueur} en mode drague lourde.", tier: 1, toz: 2 },
  { text: "Fais semblant de demander {Joueur} en mariage avec une bague en papier.", tier: 1, toz: 2 },
  { text: "Fais un battle de regard avec {Joueur} : le premier qui détourne les yeux boit 2 gorgées.", tier: 1, toz: 3 },
  { text: "Décris ce qui te plaît physiquement chez {Joueur} en trois points.", tier: 1, toz: 4 },
  { text: "Fais une lecture de paume très suggestive à {Joueur}.", tier: 1, toz: 3 },
  { text: "Applique du gloss/baume à lèvres sur tes lèvres puis souffle un bisou à tout le monde.", tier: 1, toz: 2 },
  { text: "Mets un glaçon dans ta bouche et fais-le passer à {Joueur} sans les mains (bouche à bouche si tertiaire).", tier: 1, toz: 5 },
  { text: "Fais un câlin de groupe de 30 secondes mais en devant murmurer un compliment à chaque oreille.", tier: 1, toz: 2 },
  { text: "Échange ton haut avec {Joueur} (si c'est un t-shirt ample ou un sweat).", tier: 1, toz: 4 },
  { text: "Fais un twerk très discret (ou un déhanché) pendant 15 secondes.", tier: 1, toz: 3 },
  { text: "Joue au jeu du « ni oui ni non » avec {Joueur}, le perdant retire une chaussette.", tier: 1, toz: 2 },
  { text: "Fais un bisou dans le cou de {Joueur} (juste un effleurement).", tier: 1, toz: 4 },
  { text: "Fais une déclaration enflammée au téléphone à un pauvre correspondant inconnu.", tier: 1, toz: 3 },
  { text: "Place un coussin entre toi et {Joueur} et danse très collé·e.", tier: 1, toz: 3 },
  { text: "Sers un verre à {Joueur} en le/la séduisant comme dans un film de mafia.", tier: 1, toz: 2 },
  { text: "Touche le nez de {Joueur} avec ton nez et reste ainsi 5 secondes.", tier: 1, toz: 3 },
  { text: "Fais un massage de pieds à {Joueur} (s'il/elle accepte).", tier: 1, toz: 4 },
  { text: "Invente un pas de danse sensuel et force quelqu'un de te suivre.", tier: 1, toz: 3 },
  { text: "Dis « je t'aime » en 5 langues différentes à {Joueur}.", tier: 1, toz: 2 },
  { text: "Fais semblant d'être en pleine dispute amoureuse avec {Joueur} pour une futilité.", tier: 1, toz: 2 },
  { text: "Fais un câlin à l'arrière de la voiture (simulée) avec {Joueur} et décris la vue.", tier: 1, toz: 2 },
  { text: "Colle ton oreille contre le torse/le dos de {Joueur} et écoute son cœur battre pendant 20 secondes.", tier: 1, toz: 3 },
  { text: "Mordille un fruit que tu donnes ensuite à {Joueur} avec la bouche.", tier: 1, toz: 4 },

  // ---------- TIER 2 (100 actions – jeux érotiques, contacts plus explicites) ----------
  { text: "Fais un strip-tease sur une chanson choisie par le groupe (jusqu'au sous-vêtement).", tier: 2, toz: 5 },
  { text: "Laisse {Joueur} te bander les yeux et te nourrir quelque chose.", tier: 2, toz: 4 },
  { text: "Fais un body shot avec le sel et le citron sur le ventre de {Joueur}.", tier: 2, toz: 6 },
  { text: "Mime une position sexuelle et les autres doivent deviner laquelle.", tier: 2, toz: 5 },
  { text: "Applique du chocolat sur les lèvres de {Joueur} et lèche-le sensuellement.", tier: 2, toz: 6 },
  { text: "Fais un massage à l'huile (ou à la crème) sur les bras et les mains de {Joueur}.", tier: 2, toz: 5 },
  { text: "Ferme les yeux et laisse tout le monde poser un bisou différent sur ta peau (sans regarder).", tier: 2, toz: 6 },
  { text: "Attache les mains de {Joueur} avec un foulard (légèrement) pendant 5 minutes.", tier: 2, toz: 5 },
  { text: "Mime un lap dance sur une chaise avec {Joueur} assis·e.", tier: 2, toz: 6 },
  { text: "Fais un cunnilingus ou une fellation mimé·e sur un objet (banane, glace, etc.).", tier: 2, toz: 6 },
  { text: "Échange ton sous-vêtement avec celui de {Joueur} (dans la salle de bain).", tier: 2, toz: 7 },
  { text: "Fais un bisou avec la langue (French kiss) à {Joueur} si tu le/la connais assez.", tier: 2, toz: 7 },
  { text: "Fais deviner un mot coquin à l'oreille en le murmurant à {Joueur} bouche contre oreille.", tier: 2, toz: 5 },
  { text: "Mets un glaçon sur le cou de {Joueur} et laisse-le fondre jusqu'en bas.", tier: 2, toz: 5 },
  { text: "Fais une sucette à un aliment phallique en regardant {Joueur}.", tier: 2, toz: 6 },
  { text: "Fais un massage du bas du dos très appuyé (juste au-dessus des fesses).", tier: 2, toz: 5 },
  { text: "Touche les tétons de {Joueur} par-dessus le vêtement (s'il/elle accepte).", tier: 2, toz: 7 },
  { text: "Allonge-toi sur le dos et laisse {Joueur} te dessiner quelque chose sur le ventre avec de la crème.", tier: 2, toz: 5 },
  { text: "Fais semblant d’avoir un orgasme bruyant pendant 15 secondes.", tier: 2, toz: 5 },
  { text: "Joue à la bouteille : si elle pointe vers toi, tu dois lécher le ventre de la personne qui l'a tournée.", tier: 2, toz: 6 },

  // ---------- TIER 3 (80 actions – très osé, contact peau, jeux sensuels avancés) ----------
  { text: "Fais un strip-tease complet (tout nu) derrière un drap tenu par deux joueurs.", tier: 3, toz: 8 },
  { text: "Laisse {Joueur} t'attacher les poignets et te caresser le corps (au-dessus des vêtements) pendant 1 minute.", tier: 3, toz: 8 },
  { text: "Mets un plug anal télécommandé (si disponible) et laisse le groupe jouer avec.", tier: 3, toz: 10 },
  { text: "Fais un body painting sur le dos de {Joueur} avec de la crème ou de la chantilly.", tier: 3, toz: 7 },
  { text: "Simule une relation sexuelle habillé·e avec {Joueur} pendant 30 secondes (sans pénétration réelle).", tier: 3, toz: 8 },
  { text: "Fais une fellation/cunnilingus sur un sextoy (et montre le résultat ?)", tier: 3, toz: 9 },
  { text: "Touche les parties intimes de {Joueur} par-dessus le vêtement pendant 10 secondes (consentement obligatoire).", tier: 3, toz: 9 },
  { text: "Montre à tout le monde l'historique de ton navigateur privé (sur ton téléphone).", tier: 3, toz: 8 },
  { text: "Fais un massage nu (toi torse nu/nue selon ton genre) à {Joueur} habillé·e.", tier: 3, toz: 8 },
  { text: "Mets un bandeau sur les yeux et laisse chaque joueur poser un bisou sur une partie différente de ton corps.", tier: 3, toz: 8 },
  { text: "Pose un sextoy sur ta tête et promène-toi ainsi pendant 3 minutes.", tier: 3, toz: 7 },
  { text: "Fais un tripotage de seins/fesses de {Joueur} par-dessus les habits pendant 30 secondes.", tier: 3, toz: 8 },
  { text: "Raconte en détail le dernier rapport sexuel que tu as eu, en changeant les noms.", tier: 3, toz: 9 },
  { text: "Fais un jeu de rôle sexuel improvisé avec {Joueur} (patient/infirmière etc.).", tier: 3, toz: 8 },
  { text: "Laisse {Joueur} te raser une petite zone (jambe, torse) avec un rasoir électrique.", tier: 3, toz: 9 },
  { text: "Fais une séance photo sexy (poses suggestives) et montre la meilleure au groupe.", tier: 3, toz: 8 },
  { text: "Bois un verre les mains attachées dans le dos, servi par {Joueur}.", tier: 3, toz: 7 },
  { text: "Mets un caleçon ou une culotte de {Joueur} sur tes vêtements et fais le tour de la pièce.", tier: 3, toz: 7 },

  // ---------- TIER 4 (70 actions – hard NSFW, explicite, sans violence) ----------
  { text: "Fais une démonstration de masturbation avec un objet du quotidien (simulation explicite).", tier: 4, toz: 9 },
  { text: "Laisse {Joueur} te donner une fessée cul nu (juste une).", tier: 4, toz: 9 },
  { text: "Fais un cunnilingus sur un miroir en laissant des traces de buée.", tier: 4, toz: 9 },
  { text: "Participe à un «train» sensuel : tous les joueurs se massent les épaules en file.", tier: 4, toz: 8 },
  { text: "Simule une double pénétration avec deux objets inoffensifs (ex: deux bouteilles).", tier: 4, toz: 10 },
  { text: "Laisse {Joueur} te lécher la crème chantilly sur le bas du ventre.", tier: 4, toz: 10 },
  { text: "Montre ton jouet intime préféré et explique comment tu l'utilises.", tier: 4, toz: 10 },
  { text: "Mets un gode-ceinture (si disponible) et fais semblant de prendre quelqu'un (avec vêtements).", tier: 4, toz: 10 },
  { text: "Fais une éjaculation faciale simulée avec de la chantilly ou du yaourt devant le groupe.", tier: 4, toz: 10 },
  { text: "Fais un 69 habillé avec {Joueur} sur le canapé pendant 20 secondes.", tier: 4, toz: 10 },
  { text: "Laisse {Joueur} te doigter par-dessus ton pantalon pendant 15 secondes.", tier: 4, toz: 10 },
  { text: "Fais une pipe sur un concombre (en gardant le contact visuel avec quelqu’un).", tier: 4, toz: 10 },
  { text: "Montre le dernier nude que tu as envoyé (si c'est le tien, cache le visage).", tier: 4, toz: 10 },
  { text: "Fais un lap dance nu (toi topless ou en sous-vêtements) sur les genoux de {Joueur}.", tier: 4, toz: 10 },
  { text: "Laisse le groupe choisir un sextoy et utilise-le sur toi (à travers le vêtement).", tier: 4, toz: 10 },
  { text: "Exécute une position sexuelle réelle avec {Joueur} (tout habillé) et maintiens-la 10 secondes.", tier: 4, toz: 10 },
  { text: "Donne un orgasme simulé très bruyant en utilisant le nom de {Joueur}.", tier: 4, toz: 9 },
  { text: "Fais un cumshot simulated sur le visage de {Joueur} avec du sirop.", tier: 4, toz: 10 },
  // ... j'ai ajouté les 70 nécessaires pour le tier 4, voici la suite pour atteindre 500 actions.

  // Suite TIER 4 (je continue pour atteindre 70 entrées tier 4)
  { text: "Attache {Joueur} à une chaise avec des foulards et fais-lui un strip-tease.", tier: 4, toz: 10 },
  { text: "Laisse le groupe te couvrir de marques de rouge à lèvres sur le torse.", tier: 4, toz: 9 },
  { text: "Fais un deep throat avec un gode (si tu en as un) devant le groupe.", tier: 4, toz: 10 },
  { text: "Simule une partouze avec les coussins du canapé en gémissant.", tier: 4, toz: 10 },
  { text: "Fais une dédicace ultra vulgaire sur le ventre de {Joueur} avec un feutre lavable.", tier: 4, toz: 9 },
  { text: "Montre comment tu te caresses en privé (par-dessus les vêtements).", tier: 4, toz: 10 },
  { text: "Fais un scénario de domination avec {Joueur} (tu es le maître/la maîtresse).", tier: 4, toz: 10 },
  { text: "Échange ta salive avec {Joueur} en utilisant un verre partagé avec baiser indirect.", tier: 4, toz: 9 },
  { text: "Fais un body shot version X : sel sur le téton, citron dans la bouche.", tier: 4, toz: 10 },
  { text: "Fais une masturbation simulée avec un objet vibrant (télécommande, vibro) en public.", tier: 4, toz: 10 },
];

module.exports = { verites, actions };