const GAME_TTL = 86400;

const GAME_STATUS = { WAITING: 'waiting', PLAYING: 'playing', ENDED: 'ended' };

const ROOM_PREFIX = 'game';

function redisKey(...parts) {
  return parts.join(':');
}

const CODE_CHARS = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

function generateCode() {
  let code = '';
  for (let i = 0; i < 6; i++) code += CODE_CHARS[Math.floor(Math.random() * CODE_CHARS.length)];
  return code;
}

const VERITE_CARDS = [
  // ───────── Drôles / Légères (1-100) ─────────
  'Raconte ta dernière recherche Google un peu honteuse.',
  'Quel est le pire cadeau que tu aies jamais reçu ?',
  'Ton talent caché le plus inutile ? On veut une démo !',
  'Quelle est la fake news la plus improbable à laquelle tu as presque cru ?',
  'Quel est le truc le plus bizarre dans ton sac en ce moment ?',
  'Décris ton plat préféré comme si c\'était une œuvre d\'art.',
  'Quelle est la pire tendance mode que tu aies suivie ?',
  'Quel bruit te fait instantanément sourire ?',
  'Quel est le pire surnom qu\'on t\'ait donné ?',
  'Si tu devais renommer une couleur, quel nom lui donnerais-tu ?',
  'Quel est le film que tu peux regarder en boucle sans t\'en lasser ?',
  'Raconte ta pire chute en public.',
  'Quel est le truc le plus absurde que tu aies commandé en ligne ?',
  'Si tu étais un animal, lequel serais-tu ?',
  'Quel est ton pire talent ? Montre-le nous.',
  'Quelle est l\'application la plus inutile sur ton téléphone ?',
  'Raconte ta pire tentative de cuisson.',
  'Quel est le mot que tu détestes entendre ?',
  'Si tu pouvais avoir un super-pouvoir inutile, lequel ?',
  'Quel est le pire film que tu aies vu jusqu\'à la fin ?',
  'Décris ton look de la journée avec une métaphore.',
  'Quelle chanson te fait honte d\'aimer ?',
  'Quel est le truc le plus paresseux que tu aies fait cette semaine ?',
  'Si tu étais un meme, lequel serais-tu ?',
  'Quelle est l\'odeur bizarre que tu aimes secrètement ?',
  'Quel est ton pire achat capillaire ?',
  'Raconte ta pire histoire de réveillon.',
  'Si tu devais manger une seule chose pour le reste de ta vie ?',
  'Quel est le passe-temps le plus ennuyeux que tu aies essayé ?',
  'Quelle est la question qui te saoule quand on te la pose ?',
  'Quel est ton guilty pleasure séries/téléréalité ?',
  'Si tu étais un personnage de dessin animé, qui serais-tu ?',
  'Quel est le pire jeu de mots que tu aies fait ?',
  'Raconte ta pire expérience chez le coiffeur.',
  'Quelle est la blague la plus nulle que tu connaisses ?',
  'Si tu devais changer de prénom, lequel choisirais-tu ?',
  'Quel est l\'objet le plus random dans ta chambre ?',
  'Décris ta vie avec un emoji.',
  'Quel est le pire conseil beauté qu\'on t\'ait donné ?',
  'Raconte ta pire expérience au restaurant.',
  'Quelle est ta phobie la plus ridicule ?',
  'Si tu étais une odeur, laquelle serais-tu ?',
  'Quel est le mot que tu dis le plus souvent dans une journée ?',
  'Raconte ta pire expérience de coiffure maison.',
  'Quelle est la chose la plus « vieux » que tu fasses ?',
  'Si tu avais une baguette magique pour un seul truc débile ?',
  'Quel est ton pire achat en soldes ?',
  'Décris ta voix avec trois adjectifs.',
  'Quelle est la pire mode de ton enfance ?',
  'Raconte ta pire tentative de bricolage.',
  'Quel est le truc le plus perché que tu aies dit en ayant sommeil ?',
  'Si tu étais un snack, lequel serais-tu ?',
  'Quel est le pire générique de film que tu connaisses ?',
  'Raconte ta pire expérience de camping.',
  'Quel bruit de bouche te rend fou/folle ?',
  'Si tu devais porter un seul vêtement pour toujours ?',
  'Quelle est la pire insulte que tu aies inventée ?',
  'Raconte ta pire chute à vélo.',
  'Quel est le plat que tout le monde aime sauf toi ?',
  'Si tu devais vivre dans une série, laquelle ?',
  'Quel est le pire cadeau que tu aies offert ?',
  'Raconte ta pire tentative de danse.',
  'Quelle est la chose que tu fais toujours à la dernière minute ?',
  'Si tu étais un instrument de musique, lequel ?',
  'Quel est ton pire réflexe le matin au réveil ?',
  'Décris ton humour en un mot.',
  'Quelle est la pire coiffure que tu aies eue ?',
  'Raconte ta pire histoire de train/bus.',
  'Quel est le truc le plus enfantin que tu fasses encore ?',
  'Si tu devais perdre un de tes cinq sens, lequel ?',
  'Quel est ton pire tic nerveux ?',
  'Raconte ta pire mésaventure avec un animal.',
  'Quelle est la pire chanson pour danser ?',
  'Si tu étais un jour de la semaine, lequel serais-tu ?',
  'Quel est le pire conseil de mode qu\'on t\'ait donné ?',
  'Raconte ta pire expérience de baignade.',
  'Quel est l\'objet du quotidien que tu détestes utiliser ?',
  'Si tu étais une couleur flashy, laquelle ?',
  'Quel est le pire jeu de société selon toi ?',
  'Raconte ta pire histoire d\'anniversaire.',
  'Quelle est ta peur la plus absurde ?',
  'Si tu étais une chanson de karaoké, laquelle ?',
  'Quel est le truc le plus geek que tu aies fait ?',
  'Raconte ta pire expérience de sport.',
  'Quelle est l\'émission que tu regardes en cachette ?',
  'Si tu devais être un personnage Disney, lequel ?',
  'Quel est ton pire défaut selon toi-même ?',
  'Raconte ta pire histoire d\'ascenseur.',
  'Quel est le pire parfum que tu aies senti ?',
  'Si tu étais une boisson, laquelle serais-tu ?',
  'Quel est le truc le plus awkward que tu aies fait en soirée ?',
  'Raconte ta pire expérience de déménagement.',
  'Quelle est la pire coupe de cheveux que tu aies eue ?',
  'Si tu devais chanter une chanson sous la douche pour toujours ?',
  'Quel est ton pire tic de langage ?',
  'Raconte ta pire histoire de réveil au monde.',
  'Quel est le pire film d\'horreur que tu aies vu ?',

  // ───────── Entre amis / Potins (101-200) ─────────
  'Quelle est la première impression honnête que tu as eue de {Joueur} ?',
  'Si notre groupe était une sitcom, quel serait ton rôle ?',
  'Qui dans la table est le plus susceptible de devenir célèbre ?',
  'Quelle est la chose la plus embarrassante que {Joueur} t\'ait vu faire ?',
  'Quel est le pire conseil que tu aies donné à quelqu\'un ici ?',
  'Si tu devais noter l\'hygiène de {Joueur} sur 10 ?',
  'Quel secret de {Joueur} connais-tu que les autres ignorent ?',
  'Qui est le plus mauvais perdant dans le groupe ?',
  'Quel est le pire voyage que tu aies fait avec quelqu\'un ici ?',
  'Qui dans la table est le plus susceptible de rater son réveil ?',
  'Quel est le plus gros drama que vous ayez vécu ensemble ?',
  'Qui est le plus radin de la bande ?',
  'Quel est le pire coloc potentiel ici selon toi ?',
  'Qui serait le meilleur en apocalypse zombie ?',
  'Quel membre du groupe a le plus de chance en tout ?',
  'Qui est le plus mauvais menteur ici ?',
  'Quel est le pire secret de groupe que tu connaisses ?',
  'Qui dans la table mériterait une série Netflix ?',
  'Quel est le plus gros fiasco de soirée entre vous ?',
  'Qui est le plus susceptible de devenir milliardaire ?',
  'Quel est ton meilleur souvenir avec {Joueur} ?',
  'Qui est le plus bordélique ici ?',
  'Quel est le pire repas que quelqu\'un ici t\'ait cuisiné ?',
  'Qui aurait la meilleure voix de radio ?',
  'Quel est le plus gros coup de folie du groupe ?',
  'Qui est le plus susceptible de pleurer devant un film ?',
  'Quel est le pire cadeau que tu aies reçu de quelqu\'un ici ?',
  'Qui serait le meilleur candidat pour Koh-Lanta ?',
  'Quel est le secret que tu n\'as jamais osé dire à {Joueur} ?',
  'Qui est le plus accro à son téléphone ?',
  'Quel est le pire karaoké que vous ayez fait ensemble ?',
  'Qui est le plus susceptible de se perdre en voiture ?',
  'Quel est le plus gros fous rires en groupe dont tu te souviennes ?',
  'Qui est le plus mauvais cuisinier ici ?',
  'Quel est le pire voyage que vous ayez fait tous ensemble ?',
  'Qui serait le meilleur professeur parmi vous ?',
  'Quel est le plus grand exploit de {Joueur} selon toi ?',
  'Qui est le plus susceptible d\'oublier un anniversaire ?',
  'Quel est le pire cadeau que tu aies vu offrir dans le groupe ?',
  'Qui est le plus grand bavard ici ?',
  'Quel est le meilleur conseil que tu aies reçu de quelqu\'un ici ?',
  'Qui est le plus susceptible de devenir YouTubeur ?',
  'Quel est le pire secret que tu aies gardé pour le groupe ?',
  'Qui est le moins sportif selon toi ?',
  'Quel est le plus gros sacrifice que tu aies fait pour un ami ici ?',
  'Qui est le plus susceptible de rater son avion ?',
  'Quel est le pire surnom que vous vous donnez dans le groupe ?',
  'Qui aurait la meilleure émission de talk-show ?',
  'Quel est le plus beau geste de {Joueur} envers toi ?',
  'Qui est le plus susceptible de se disputer pour rien ?',
  'Quel est le plus grand malentendu que vous ayez eu ?',
  'Qui est le plus susceptible de commander une pizza à 3h du matin ?',
  'Quel est le pire coloc que vous ayez eu dans le groupe ?',
  'Qui est le plus sage et le plus fou de la bande ?',
  'Quel est ton pire souvenir avec quelqu\'un ici ?',
  'Qui est le plus susceptible de se faire arrêter à la douane ?',
  'Quel est le plus beau compliment que quelqu\'un ici t\'ait fait ?',
  'Qui est le plus susceptible de devenir acteur/actrice ?',
  'Quel est le pire mensonge que quelqu\'un ici ait cru de toi ?',
  'Qui est le plus susceptible de gagner un concours de danse ?',
  'Quel est le meilleur moment de rigolade avec {Joueur} ?',
  'Qui est le plus susceptible d\'avoir un coup de foudre ?',
  'Quel est le pire jeu auquel vous ayez joué tous ensemble ?',
  'Qui est le plus mauvais conducteur ici ?',
  'Quel est le plus grand exploit sportif de quelqu\'un ici ?',
  'Qui est le plus susceptible de se lever tôt même en vacances ?',
  'Quel est le moment le plus gênant que tu aies vécu avec le groupe ?',
  'Qui est le plus susceptible de devenir vegan ?',
  'Quel est le pire film que vous ayez regardé tous ensemble ?',
  'Qui est le plus susceptible de chanter sous la douche ?',
  'Quel est le plus beau trait de caractère de {Joueur} ?',
  'Qui est le plus susceptible d\'avoir un compte secret sur les réseaux ?',
  'Quel est le pire accident de {Joueur} dont tu te souviennes ?',
  'Qui est le plus susceptible de parier sur n\'importe quoi ?',
  'Quel est le plus gros fail du groupe en public ?',
  'Qui est le plus susceptible de devenir musicien ?',
  'Quel est le meilleur inside joke du groupe ?',
  'Qui est le plus susceptible de se faire virer d\'un resto ?',
  'Quel est le moment où tu as eu le plus honte de {Joueur} ?',
  'Qui est le plus susceptible de sauver une vie en héros ?',
  'Quel est le plus gros gâchis que vous ayez fait en cuisine ?',
  'Qui est le plus susceptible de porter une tenue bizarre ?',
  'Quel est le plus grand changement chez quelqu\'un ici depuis que tu le connais ?',
  'Qui est le plus susceptible de rénover sa maison lui-même ?',
  'Quel est le pire achat commun que vous ayez fait ?',
  'Qui est le plus susceptible de devenir chef/cheffe ?',
  'Quel est le plus gros fiasco amoureux chez quelqu\'un ici ?',
  'Qui est le plus susceptible de s\'expatrier ?',
  'Quel est le meilleur talent caché de quelqu\'un ici ?',
  'Qui est le plus susceptible de s\'endormir en soirée ?',
  'Quel est le moment où tu as le plus ri avec {Joueur} ?',
  'Qui est le plus susceptible de conduire comme un fou ?',
  'Quel est le plus beau voyage que vous ayez fait ensemble ?',
  'Qui est le plus susceptible de devenir influenceur ?',
  'Quel est le pire défaut de {Joueur} selon tout le monde ?',
  'Qui est le plus susceptible de se marier en premier ?',
  'Quel est le plus grand mystère du groupe ?',

  // ───────── Croustillants / Perso (201-350) ─────────
  'Quelle est la chose la plus folle que tu aies faite sur un coup de tête ?',
  'Le plus gros mensonge que tu aies raconté à tes parents ?',
  'Raconte ton rendez-vous le plus gênant.',
  'As-tu déjà eu un crush sur quelqu\'un dans cette pièce ?',
  'Quel est ton guilty pleasure ultime ?',
  'Si ta vie sentimentale était un film, quel titre ?',
  'Quel est le pire date de ta vie ?',
  'As-tu déjà regretté d\'avoir couché avec quelqu\'un ?',
  'Quelle est la chose la plus embarrassante qu\'on t\'ait vue faire ?',
  'Quel est le plus gros risque que tu aies pris pour l\'amour ?',
  'Raconte ton pire plan cul.',
  'Quelle est la pire rupture que tu aies vécue ?',
  'As-tu déjà eu une relation à distance ? Comment ça s\'est passé ?',
  'Quel est ton plus gros regret sentimental ?',
  'As-tu déjà embrassé quelqu\'un par défi ?',
  'Quelle est la pire déclaration d\'amour que tu aies faite ?',
  'As-tu déjà eu un coup de foudre ? Raconte.',
  'Quelle est la chose la plus romantique que tu aies faite ?',
  'As-tu déjà menti pour impressionner quelqu\'un ?',
  'Quel est le pire rencard que tu aies organisé ?',
  'As-tu déjà eu un crush sur un prof ?',
  'Quelle est la pire technique de drague qu\'on t\'ait faite ?',
  'As-tu déjà embrassé quelqu\'un par erreur ?',
  'Raconte ton plus gros coup de cœur.',
  'As-tu déjà pleuré à cause d\'une rupture ? Devant qui ?',
  'Quel est le pire message que tu aies envoyé en soirée ?',
  'As-tu déjà ghosté quelqu\'un ? Pourquoi ?',
  'Quel est ton pire date organisé par des amis ?',
  'As-tu déjà eu un crush sur un ami ?',
  'Raconte le jour où tu as eu le cœur brisé.',
  'Quel est ton plus gros deal-breaker en amour ?',
  'As-tu déjà fait le premier pas ? Comment ?',
  'Quelle est la pire question qu\'on t\'ait posée sur ta vie amoureuse ?',
  'As-tu déjà eu une aventure avec un collègue ?',
  'Quel est le plus gros mensonge que tu aies dit pour séduire ?',
  'As-tu déjà été surpris en train de draguer ?',
  'Quelle est la pire phrase que tu aies dite lors d\'un rencard ?',
  'As-tu déjà eu un coup d\'un soir ? Raconte.',
  'Quel est ton pire souvenir de Saint-Valentin ?',
  'As-tu déjà regretté d\'avoir embrassé quelqu\'un ?',
  'Quelle est la chose la plus bizarre qui t\'excite chez quelqu\'un ?',
  'As-tu déjà eu une relation avec quelqu\'un de beaucoup plus âgé ?',
  'Quel est le pire compliment que tu aies reçu ?',
  'As-tu déjà fait semblant d\'aimer quelqu\'un ?',
  'Quelle est la pire rupture que tu aies infligée ?',
  'As-tu déjà stalké un ex ? Jusqu\'où ?',
  'Quel est le plus gros coup de foudre de ta vie ?',
  'As-tu déjà eu une dispute en public avec un ex ?',
  'Quelle est la pire qualité que tu recherches chez quelqu\'un ?',
  'As-tu déjà utilisé une appli de rencontre ? Raconte.',
  'Quel est le pire profil que tu aies vu sur une appli ?',
  'As-tu déjà eu un date qui a mal tourné à cause de toi ?',
  'Quelle est la pire excuse que tu aies donnée pour rompre ?',
  'As-tu déjà eu un crush sur un ami de votre groupe ?',
  'Quel est le record du plus long temps sans bisou ?',
  'As-tu déjà fait une déclaration en public ?',
  'Quelle est la chose la plus kinky que tu aies essayée ?',
  'As-tu déjà eu une relation avec quelqu\'un du même sexe ?',
  'Quel est le pire endroit où tu aies embrassé quelqu\'un ?',
  'As-tu déjà été friendzoné ? Raconte.',
  'Quel est le plus gros red flag que tu ignores chez quelqu\'un ?',
  'As-tu déjà fait semblant d\'être quelqu\'un d\'autre sur Internet ?',
  'Quelle est la pire raison pour laquelle tu as rompu ?',
  'As-tu déjà eu une histoire avec un inconnu rencontré en soirée ?',
  'Quel est ton plus gros fantasme inavouable ?',
  'As-tu déjà regretté de ne pas avoir fait le premier pas ?',
  'Quelle est la pire séparation que tu aies vécue ?',
  'As-tu déjà pleuré pendant un film romantique ?',
  'Quel est le pire cadeau de Saint-Valentin que tu aies reçu ?',
  'As-tu déjà couché avec quelqu\'un dès le premier soir ?',
  'Quelle est la pire insulte que tu aies reçue en amour ?',
  'As-tu déjà eu une aventure d\'été ? Ça a duré combien de temps ?',
  'Quel est ton plus gros deal-breaker physique ?',
  'As-tu déjà été amoureux de quelqu\'un qui ne le savait pas ?',
  'Quelle est la pire jalousie que tu aies ressentie ?',
  'As-tu déjà créé un faux profil pour tester quelqu\'un ?',
  'Quel est le pire anniversaire en couple que tu aies passé ?',
  'As-tu déjà eu une relation avec deux personnes en même temps ?',
  'Quelle est la pire dispute que tu aies eue en couple ?',
  'As-tu déjà espionné le téléphone de ton partenaire ?',
  'Quel est le plus gros sacrifice que tu aies fait en amour ?',
  'As-tu déjà eu un plan cul régulier ?',
  'Quelle est la pire phrase que tu aies dite pendant l\'amour ?',
  'As-tu déjà regretté une rupture ?',
  'Quel est ton pire souvenir avec un ex ?',
  'As-tu déjà eu un crush sur quelqu\'un de célèbre ?',
  'Quelle est la chose la plus folle que tu aies faite pour un ex ?',
  'As-tu déjà eu une relation ouverte ?',
  'Quel est le plus gros mensonge que ton ex t\'ait dit ?',
  'As-tu déjà fait un enfant à quelqu\'un / été enceinte ?',
  'Quelle est la pire chose que tu aies dite pendant un rencard ?',
  'As-tu déjà dragué quelqu\'un pour faire rire tes amis ?',
  'Quel est ton plus gros regret en amour ?',
  'As-tu déjà eu un coup de foudre dans les transports ?',
  'Quelle est la pire chose que tu acceptes chez un partenaire ?',
  'As-tu déjà eu une relation avec un de tes meilleurs amis ?',
  'Quel est le plus beau compliment que tu aies reçu en amour ?',
  'As-tu déjà embrassé quelqu\'un pour oublier un ex ?',
  'Quelle est la pire trahison amoureuse que tu aies vécue ?',
  'As-tu déjà eu un rendez-vous arrangé par la famille ?',
  'Quel est le plus gros risque que tu prendrais pour l\'amour ?',
  'As-tu déjà eu une relation avec quelqu\'un de ton travail ?',
  'Quelle est la chose la plus sexy qu\'on puisse te dire ?',
  'As-tu déjà trompé ? Si oui, dans quelles circonstances ?',
  'Quel est ton plus grand fantasme pour un date parfait ?',
  'As-tu déjà sorti avec quelqu\'un que tes amis désapprouvaient ?',
  'Quelle est la pire habitude de ton ex que tu détestais ?',
  'As-tu déjà couché avec quelqu\'un lors d\'un voyage ?',
  'Quel est le plus gros smiley que tu utilises en draguant ?',
  'As-tu déjà été amoureux en cachette ? De qui ?',
  'Quelle est la pire question que tu poses en rencard ?',
  'As-tu déjà eu un date qui a duré plus de 24h ?',
  'Quel est le plus gros secret que tu caches sur ta vie amoureuse ?',
  'As-tu déjà eu un coup de foudre qui a duré ?',
  'Quelle est la pire qualité que tu recherches chez un partenaire ?',
  'As-tu déjà flirté pour obtenir quelque chose ?',
  'Quel est ton plus gros turn-off en amour ?',
  'As-tu déjà eu une histoire avec quelqu\'un de la famille d\'un ami ?',
  'Quelle est la chose la plus étrange qui t\'attire physiquement ?',
  'As-tu déjà eu des sentiments pour un professeur ?',
  'Quel est le plus gros mensonge que tu aies raconté pour plaire ?',
  'As-tu déjà pleuré pendant un breakup ? Devant la personne ?',
  'Quelle est la pire rupture que tu aies faite par SMS ?',
  'As-tu déjà eu un plan à trois ?',
  'Quel est le pire endroit où tu aies embrassé quelqu\'un ?',
  'As-tu déjà regretté de ne pas avoir couché avec quelqu\'un ?',
  'Quelle est la personne que tu aurais dû embrasser mais tu ne l\'as pas fait ?',
  'As-tu déjà fait l\'amour dans un endroit public ?',
  'Quel est le plus gros deal-breaker que tu aies ignoré ?',
  'As-tu déjà eu un ex toxique ? Raconte.',
  'Quelle est la pire dispute pour une broutille que tu aies eue ?',

  // ───────── Hot / Osées (351-450) ─────────
  'Quelle est la partie du corps que tu regardes en premier chez {Joueur} ?',
  'Qu\'est-ce qui te fait craquer chez une personne ? (3 choses)',
  'Quel est le compliment le plus marquant qu\'on t\'ait jamais fait ?',
  'Décris ton look le plus séduisant que tu aies jamais porté.',
  'Quelle est la chose la plus osée que tu aies faite pour séduire ?',
  'Quel défaut physique trouves-tu bizarrement attirant chez quelqu\'un ?',
  'Si tu devais passer une soirée en tête-à-tête avec {Joueur}, où irais-tu ?',
  'Quel est le type de lingerie que tu préfères ?',
  'Quelle est la partie de ton corps que tu assumes le plus ?',
  'Quel est le vêtement qui te rend le plus sexy ?',
  'Si tu devais décrire ton style sexuel avec une couleur ?',
  'Qu\'est-ce qui te met le plus dans l\'ambiance ?',
  'Quel est ton endroit préféré pour être embrassé ?',
  'Quelle est la chose la plus sensuelle qu\'on puisse faire sans se toucher ?',
  'Quel est le mot qui te fait le plus d\'effet ?',
  'Quel type de baiser préfères-tu ?',
  'Quelle est la musique qui te met dans une ambiance chaude ?',
  'Décris ton parfum idéal sur un partenaire.',
  'Quel est le regard qui te fait fondre ?',
  'Quelle est la première chose que tu remarques quand tu entres dans une pièce ?',
  'Si tu devais choisir une célébrité pour une nuit ?',
  'Quel est le compliment qui te fait rougir à coup sûr ?',
  'Quelle est la partie du corps que tu aimes qu\'on embrasse chez toi ?',
  'Qu\'est-ce qui te rend le plus attirant selon toi ?',
  'Quel est le truc le plus hot qu\'on puisse te chuchoter ?',
  'Quelle est la tenue que tu trouves irrésistible chez les autres ?',
  'Quel est le geste le plus séduisant qu\'on puisse faire ?',
  'Si tu devais utiliser un seul mot pour décrire ton style ?',
  'Quelle est la chose la plus sensuelle dans le quotidien ?',
  'Qu\'est-ce qui te fait trembler des genoux ?',
  'Quel est le type de regard qui te fait craquer ?',
  'Quelle est la partie du corps que tu trouves la plus sexy chez l\'homme/la femme ?',
  'Quel est le défaut que tu trouves charmant chez quelqu\'un ?',
  'Si tu devais choisir une voix pour te réveiller chaque matin ?',
  'Quel est ton plus gros turn-on ?',
  'Quelle est l\'odeur qui te rend complètement fou/folle ?',
  'Quel est le bruit qui te donne des frissons ?',
  'Décris ton idéal de beauté en trois mots.',
  'Quelle est la chose la plus érotique que tu aies vue ?',
  'Qu\'est-ce qui te fait le plus craquer chez {Joueur} ?',
  'Quel est ton plus gros fantasme de voyage romantique ?',
  'Quelle est la chose la plus sexy dans une routine quotidienne ?',
  'Si tu devais choisir entre le regard et le sourire ?',
  'Quel est le style vestimentaire qui te fait de l\'effet ?',
  'Décris le baiser parfait selon toi.',
  'Quelle est la chose la plus chaude qu\'on puisse faire avec les yeux ?',
  'Quel est ton plus gros crush cinéma ?',
  'Quelle est la partie de ton corps que tu aimes qu\'on touche ?',
  'Si tu devais choisir un accessoire pour être plus sexy ?',
  'Quel est le compliment que tu aimerais recevoir plus souvent ?',
  'Qu\'est-ce qui te donne confiance en toi ?',
  'Quel est le plus beau corps que tu aies vu en vrai ?',
  'Quelle est la voix qui te fait de l\'effet ?',
  'Si tu devais décrire ton style au lit en un mot ?',
  'Quel est le plat le plus aphrodisiaque selon toi ?',
  'Qu\'est-ce qui te fait rougir le plus vite ?',
  'Quel est le type de caresse que tu préfères ?',
  'Si tu devais être une fleur pour séduire ?',
  'Quelle est la première chose que tu regardes chez quelqu\'un ?',
  'Quel est le pire défaut chez un partenaire ?',
  'Décris ton crush parfait.',
  'Quel est le plus beau compliment que tu aies reçu sur ton corps ?',
  'Qu\'est-ce qui te fait le plus craquer chez quelqu\'un de timide ?',
  'Si tu devais perdre un sens pour gagner en séduction ?',
  'Quel est ton pire défaut en séduction ?',
  'Quelle est la chose la plus sexy selon toi dans la confiance ?',
  'Si tu devais choisir une matière qui représente ta peau ?',
  'Quelle est la partie la plus sensible de ton corps ?',
  'Quel est le geste le plus tendre que tu connaisses ?',
  'Décris l\'endroit parfait pour un rendez-vous romantique.',
  'Quel est le type de chaleur que tu préfères ? (corps, feu, soleil)',
  'Qu\'est-ce qui te fait le plus d\'effet dans un regard ?',
  'Si tu devais garder un seul sens pour faire l\'amour ?',
  'Quelle est la chose la plus audacieuse que tu aimerais essayer ?',
  'Quel est le plus gros détail qui tue chez quelqu\'un ?',
  'Décris ton style de baiser.',
  'Quelle est la partie la plus douce de ton corps ?',
  'Si tu devais être une musique d\'ambiance ?',
  'Qu\'est-ce qui te fait le plus craquer dans une voix ?',
  'Quel est le mot le plus sexy de la langue française ?',
  'Si tu devais décrire ton regard en un mot ?',
  'Quelle est la première chose que tu fais quand tu plais à quelqu\'un ?',
  'Quel est le plus grand boost de confiance que tu aies eu ?',
  'Décris la texture que tu préfères sur une peau.',
  'Quel est le plus beau moment de séduction que tu aies vécu ?',
  'Si tu devais faire un strip sur quelle musique ?',
  'Quelle est la partie de ton visage que tu trouves la plus attirante ?',
  'Quel est le plus beau sourire que tu aies vu ?',
  'Qu\'est-ce qui te rend unique dans ta façon de séduire ?',
  'Si tu devais inventer une nouvelle façon d\'embrasser ?',
  'Quelle est l\'émotion la plus sexy selon toi ?',
  'Quel est le plus grand mystère de la séduction pour toi ?',
  'Décris ton look de soirée idéal.',
  'Quelle est la phrase d\'accroche qui marche sur toi ?',
  'Si tu devais être un tatouage, où et quoi ?',
  'Quelle couleur te rend le plus attirant(e) ?',
  'Quel est le regard le plus séduisant de la table ?',
  'Si tu devais choisir entre une voix chaude ou des mains douces ?',
  'Qu\'est-ce qui te fait le plus d\'effet chez {Joueur} ?',
  'Quel est le super-pouvoir qui te rendrait ultra séduisant ?',

  // ───────── Inconfortables / Extrêmes (451-500) ─────────
  'Quelle est la dernière fois que tu as menti à quelqu\'un dans cette pièce ?',
  'As-tu déjà fouillé dans le téléphone de quelqu\'un ?',
  'Qui est la personne que tu aimes le moins ici ?',
  'As-tu déjà volé quelque chose ? Quoi ?',
  'Combien de temps as-tu tenu sans te doucher ? Sois honnête.',
  'As-tu déjà envoyé des nudes ? À qui ?',
  'Quelle est ta plus grande peur inavouable ?',
  'As-tu déjà simulé un orgasme ?',
  'Quelle est la pire chose que tu aies faite par jalousie ?',
  'As-tu déjà eu des pensées sexuelles sur quelqu\'un ici ?',
  'Quel est le plus gros secret que tu caches à tes proches ?',
  'As-tu déjà fait quelque chose d\'illégal sans te faire prendre ?',
  'Quelle est la pire trahison que tu aies commise ?',
  'As-tu déjà stalké quelqu\'un des heures sur les réseaux ?',
  'Quel est le pire défaut de {Joueur} selon toi ?',
  'As-tu déjà regretté quelque chose que tu as fait dans cette soirée ?',
  'Quelle est la pire insulte que tu aies dite à quelqu\'un ?',
  'As-tu déjà fait semblant d\'être plus riche que tu ne l\'es ?',
  'Quel est le pire mensonge que tu aies dit aujourd\'hui ?',
  'As-tu déjà eu des ennuis avec la justice ?',
  'Quelle est la chose la plus crade que tu aies faite ?',
  'As-tu déjà été viré d\'un établissement ?',
  'Quel est le plus gros risque que tu aies pris sans réfléchir ?',
  'As-tu déjà eu un accident embarrassant en public ?',
  'Quelle est la pire rumeur que tu aies lancée ?',
  'As-tu déjà fait une chose humiliante pour de l\'argent ?',
  'Quel est le plus gros caprice que tu aies fait en public ?',
  'As-tu déjà pleuré au travail / à l\'école ?',
  'Quelle est la chose la plus hypocrite que tu aies faite ?',
  'As-tu déjà fait un cauchemar sur quelqu\'un ici ?',
  'Quel est le plus grand échec de ta vie ?',
  'As-tu déjà frappé quelqu\'un ?',
  'Quelle est la pire addiction que tu caches ?',
  'As-tu déjà menti sur ton âge pour plaire ?',
  'Quel est le pire conseil que tu aies suivi ?',
  'As-tu déjà cassé un couple ?',
  'Quelle est la chose la plus lâche que tu aies faite ?',
  'As-tu déjà été suivi par quelqu\'un ?',
  'Quelle est la plus grosse bêtise de ton enfance ?',
  'As-tu déjà conduit en état d\'ébriété ?',
  'Quel est le pire mensonge sur ton CV ?',
  'As-tu déjà fait une fausse couche / mis quelqu\'un enceinte ?',
  'Quelle est la pire dispute que tu aies eue avec un inconnu ?',
  'As-tu déjà séché des cours/le travail pour une mauvaise raison ?',
  'Quel est le plus gros reproche qu\'on te fasse souvent ?',
  'As-tu déjà gâché une amitié pour une histoire de cul ?',
  'Quelle est la chose la plus raciste / sexiste que tu aies dite ?',
  'As-tu déjà eu une ITS ?',
  'Quel est le plus gros fiasco financier de ta vie ?',
  'As-tu déjà fait quelque chose par dépit ?',
  'Quelle est la pire corvée que tu aies faite pour de l\'argent ?',
  'As-tu déjà eu une expérience paranormale ?',
  'Quel est le plus grand bobard que tu aies raconté pour te vanter ?',
  'As-tu déjà fait semblant d\'être malade pour éviter quelque chose ?',
  'Quelle est la pire nuit blanche de ta vie ?',
  'As-tu déjà eu une aventure avec quelqu\'un de beaucoup plus jeune ?',
  'Quel est le pire mensonge que tu aies dit à ton médecin ?',
  'As-tu déjà espionné une conversation privée ?',
  'Quelle est la pire chose que tu aies faite en voiture ?',
  'As-tu déjà menti sur ton état civil ?',
  'Quel est le pire pétage de plomb que tu aies eu ?',
  'As-tu déjà été accusé de quelque chose que tu n\'as pas fait ?',
  'Quelle est la pire vengeance que tu aies faite ?',
  'As-tu déjà fait quelque chose d\'illégal par amitié ?',
  'Quel est le pire cadeau que tu aies refilé à quelqu\'un ?',
  'As-tu déjà pleuré au cinéma devant tout le monde ?',
  'Quelle est la pire gêne que tu aies eue en rendez-vous ?',
  'As-tu déjà fait une promesse que tu savais ne pas tenir ?',
  'Quel est le plus grand sacrifice que tu aies fait pour un secret ?',
  'As-tu déjà eu une peur bleue de quelque chose de ridicule ?',
  'Quelle est la pire dispute en public que tu aies eue ?',
  'As-tu déjà regretté d\'avoir été honnête ?',
  'Quel est le pire concours de circonstances de ta vie ?',
  'As-tu déjà eu une réaction disproportionnée ?',
  'Quelle est la chose la plus embarrassante que tes parents aient faite devant tes amis ?',
  'As-tu déjà triché à un test de personnalité ?',
  'Quel est le plus gros mensonge que tu aies dit pour éviter une fête ?',
  'As-tu déjà fait semblant d\'être occupé pour ne pas voir quelqu\'un ?',
  'Quelle est la pire excuse que tu aies donnée pour quitter une soirée ?',
  'As-tu déjà fait semblant d\'aimer un cadeau ?',
  'Quelle est la pire vanne que tu aies lancée en public ?',
  'As-tu déjà fait semblant d\'être heureux pour quelqu\'un ?',
  'Quel est le pire lapsus que tu aies fait ?',
  'As-tu déjà eu un trou de mémoire gênant ?',
  'Quelle est la pire bourde que tu aies dite devant un patron ?',
  'As-tu déjà fait semblant de connaître quelqu\'un ?',
  'Quel est le pire prénom que tu aurais pu avoir ?',
  'As-tu déjà eu un fou rire dans un endroit sérieux ?',
  'Quelle est la pire tache que tu n\'aies jamais réussi à enlever ?',
  'As-tu déjà fait une blague qui s\'est retournée contre toi ?',
];

const ACTION_CARDS = [
  // ───────── Drôles / Ridicules (1-100) ─────────
  'Fais la chenille tout seul autour du groupe.',
  'Parle comme Yoda jusqu\'à ton prochain tour.',
  'Imite le démarrage d\'un vieux modem 56k.',
  'Fais une battle de regards avec {Joueur}. Le premier qui rit a perdu.',
  'Récite l\'alphabet à l\'envers le plus vite possible.',
  'Fais le moonwalk sur 3 mètres.',
  'Mange un biscuit sans utiliser tes mains.',
  'Fais le bruitage d\'un personnage de jeu vidéo connu.',
  'Fais un câlin de 10 secondes à {Joueur} sans dire un mot.',
  'Laisse {Joueur} te coiffer de manière ridicule.',
  'Parle avec un accent marseillais jusqu\'à ton prochain tour.',
  'Fais le cri de la mouette 3 fois de suite.',
  'Imite un robot qui apprend à danser.',
  'Garde la pose de la statue pendant 30 secondes.',
  'Fais semblant d\'être un chat qui se lèche la patte.',
  'Raconte une blague en la chantant.',
  'Fais une imitation de ta mère / de ton père.',
  'Mange un quartier de citron sans faire de grimace.',
  'Parle sans arrêter de cligner des yeux pendant 1 minute.',
  'Fais le bruit d\'une cocotte-minute qui siffle.',
  'Imite la marche d\'un manchot.',
  'Chante ta réponse à la question suivante au lieu de parler.',
  'Fais semblant d\'être un serpent qui rampe.',
  'Tiens ton verre avec le petit doigt en l\'air jusqu\'au prochain tour.',
  'Fais le cri du coq le plus fort possible.',
  'Mime quelqu\'un qui se brûle la langue.',
  'Fais une bataille de pouces avec {Joueur}. Perdant = gorgée.',
  'Raconte une histoire en n\'utilisant que des onomatopées.',
  'Imite un professeur ennuyeux.',
  'Fais un selfie avec la tête de {Joueur} en arrière-plan.',
  'Mime un personnage de jeu vidéo qui saute sur place.',
  'Garde un crayon entre le nez et la lèvre pendant 1 minute.',
  'Fais le bruit d\'une voiture qui démarre par grand froid.',
  'Danse comme si tu étais dans un clip des années 80.',
  'Imite une mouche qui se cogne contre une vitre.',
  'Récite le refrain d\'une chanson enfantine à l\'envers.',
  'Fais une déclaration d\'amour à une chaise.',
  'Parle en rimes jusqu\'à ton prochain tour.',
  'Fais deviner ton film préféré en le mimant.',
  'Imite un joueur de tennis en plein match.',
  'Fais la grenouille (accroupi, mains au sol) pendant 10 secondes.',
  'Choisis un objet dans la pièce et fais-lui un discours.',
  'Fais semblant d\'être un présentateur météo déchaîné.',
  'Imite le bruit d\'un dinosaure.',
  'Mime quelqu\'un qui marche sur des œufs.',
  'Fais un playback de n\'importe quelle chanson choisie par le groupe.',
  'Imite une personne âgée qui cherche ses lunettes.',
  'Fais la roue ou essaie. L\'intention compte.',
  'Reste immobile comme une statue pendant que les autres te chatouillent.',
  'Fais deviner un mot les yeux fermés en le dessinant dans l\'air.',
  'Parle la bouche pleine d\'eau sans recracher.',
  'Imite un bébé qui pleure.',
  'Fais 5 tours sur toi-même, puis marche en ligne droite.',
  'Imite un cheval au galop.',
  'Mime quelqu\'un qui mange une pizza brûlante.',
  'Fais le poirier contre le mur (avec aide) pendant 10 secondes.',
  'Imite un robot défectueux.',
  'Fais une chorégraphie sur une sonnerie de téléphone.',
  'Mime la cuisson d\'un œuf.',
  'Imite un acteur de film muet.',
  'Fais le bruit d\'un orchestre qui s\'accorde.',
  'Danse comme un crabe pendant 15 secondes.',
  'Imite une personne qui se réveille en retard.',
  'Fais semblant de conduire une voiture de course.',
  'Mime une partie de bowling imaginaire.',
  'Imite un joueur de golf qui rate son coup.',
  'Fais le bruit d\'un micro-ondes qui sonne.',
  'Parle avec une voix d\'outre-tombe jusqu\'à ton prochain tour.',
  'Fais une imitation du cri de Tarzan.',
  'Mime une personne qui se noie dans une piscine imaginaire.',
  'Imite un enfant qui fait un caprice.',
  'Fais deviner un métier en le mimant.',
  'Danse comme si tu avais des fourmis dans le pantalon.',
  'Imite un vampire qui entre dans une église.',
  'Fais le bruit d\'un cheval au galop avec ta bouche.',
  'Mime quelqu\'un qui essaie d\'attraper un moustique.',
  'Imite une star du rock qui fait un solo de guitare.',
  'Fais le bruit d\'une foule en délire.',
  'Mime un pompier qui éteint un incendie.',
  'Imite un mannequin sur un podium de mode.',
  'Fais la vague tout seul autour de la table.',
  'Mime un détective privé qui suit une cible.',
  'Imite une personne qui a gagné au loto.',
  'Fais une sérénade imaginaire sous une fenêtre.',
  'Mime un cuisinier qui rate sa recette.',
  'Imite un singe qui mange une banane.',
  'Fais le bruit d\'un aspirateur.',
  'Mime un jardinier qui arrose ses plantes.',
  'Imite un pilote d\'avion qui annonce des turbulences.',
  'Fais la mascotte d\'une équipe sportive imaginaire.',
  'Mime un plongeur qui saute dans l\'eau.',
  'Imite une personne qui fait du ski nautique.',
  'Fais semblant de lancer une pêche et de remonter un gros poisson.',
  'Mime un cow-boy qui dompte un cheval.',
  'Imite un super-héros qui atterrit après un vol.',
  'Fais le bruit d\'un chat qui ronronne.',
  'Mime un cambrioleur qui essaie d\'ouvrir un coffre.',
  'Imite un reporter en direct d\'un événement absurde.',
  'Fais une tentative de breakdance (même ratée).',

  // ───────── Entre amis / Liens (101-200) ─────────
  'Donne ton téléphone à {Joueur} qui peut envoyer un émoji au 1er contact.',
  'Raconte une histoire en utilisant des titres de chansons.',
  'Imite un membre du groupe, les autres devinent qui c\'est.',
  'Fais un compliment très spécifique à chaque personne.',
  'Laisse {Joueur} fouiller ton historique YouTube 30 secondes.',
  'Échange un vêtement avec {Joueur} jusqu\'à la prochaine carte.',
  'Mime un film et les autres doivent deviner.',
  'Fais un discours d\'1 min sur un sujet improbable.',
  'Appelle un ami au hasard et dis-lui « Je t\'aime ».',
  'Laisse le groupe choisir ta photo de profil pour 1h.',
  'Poste une story mystérieuse sur ton réseau social.',
  'Laisse {Joueur} envoyer un message depuis ton téléphone à qui il veut.',
  'Fais un aveu à voix haute : le pire défaut de {Joueur}.',
  'Donne ton téléphone à {Joueur} pour qu\'il like les 3 premières photos du compte qu\'il veut.',
  'Fais un compliment sur le style vestimentaire de chaque joueur.',
  'Appelle un contact et fais-lui une devinette débile.',
  'Laisse {Joueur} choisir un filtre Instagram et prends un selfie.',
  'Échange ton siège avec {Joueur} pour les 3 prochains tours.',
  'Fais un massage de 30 secondes à {Joueur}.',
  'Raconte la pire blague que tu connaisses. Si personne rit, gorgée.',
  'Laisse le groupe décider d\'un nouveau surnom pour toi ce soir.',
  'Fais une photo imitant la personne à ta droite.',
  'Raconte un secret que tu n\'as jamais partagé avec le groupe.',
  'Choisis la personne la plus drôle ici selon toi.',
  'Fais un câlin collectif à tout le groupe.',
  'Donne à {Joueur} le droit de poser une question à ton ex par SMS.',
  'Fais un top 3 de tes amis ici du plus sage au plus fou.',
  'Regarde {Joueur} dans les yeux et dis-lui ce que tu apprécies le plus chez lui.',
  'Organise un mini-concours de grimaces avec {Joueur}.',
  'Imite l\'accent de quelqu\'un du groupe.',
  'Fais deviner au groupe qui est ta célébrité préférée en la mimant.',
  'Laisse {Joueur} envoyer un vocal sur le groupe WhatsApp.',
  'Porte {Joueur} sur ton dos pendant 10 secondes (si possible).',
  'Fais un compliment sur le sourire de quelqu\'un ici.',
  'Raconte la première impression que tu as eue de quelqu\'un ici.',
  'Laisse le groupe choisir ta coiffure pour le reste de la soirée.',
  'Fais deviner ton âge à {Joueur} en le regardant dans les yeux.',
  'Danse un slow avec {Joueur} sur une musique imaginaire.',
  'Dis 3 choses que tu aimes chez {Joueur}.',
  'Laisse {Joueur} t\'habiller avec un accessoire ridicule de son choix.',
  'Fais un duel de danse avec {Joueur} pendant 20 secondes.',
  'Appelle tes parents et dis-leur que tu as rencontré quelqu\'un.',
  'Fais une devinette : si personne ne trouve, tu bois.',
  'Donne ton téléphone à {Joueur} pour envoyer un message à ta mère.',
  'Fais un compliment sur l\'intelligence de quelqu\'un ici.',
  'Laisse le groupe lire ton dernier SMS envoyé.',
  'Dis à chaque joueur ce que tu changerais chez lui (bienveillant).',
  'Organise un bras de fer avec {Joueur}.',
  'Fais un câlin de groupe de 10 secondes.',
  'Raconte la dernière fois que tu as pleuré devant quelqu\'un ici.',
  'Laisse {Joueur} te faire une critique constructive.',
  'Fais un défilé de mode avec {Joueur} sur une musique.',
  'Imite la façon de rire de quelqu\'un ici.',
  'Fais deviner ton plus grand rêve en le mimant.',
  'Dis à chaque joueur ce que tu aimerais apprendre de lui.',
  'Fais une photo de groupe où tu fais la tête.',
  'Laisse {Joueur} fouiller ton téléphone 15 secondes.',
  'Fais un cadeau imaginaire à chaque joueur.',
  'Raconte la pire chose que tu aies faite avec quelqu\'un ici.',
  'Fais un jeu du regard avec {Joueur} sans rire.',
  'Laisse quelqu\'un te maquiller / te dessiner sur le visage.',
  'Fais une déclaration d\'amitié à chaque joueur.',
  'Appelle ton meilleur ami et dis-lui « Tu es important pour moi ».',
  'Mime le métier rêvé de quelqu\'un ici.',
  'Choisis la personne la plus stylée ici.',
  'Fais un duel de pouces avec {Joueur}.',
  'Raconte la dernière fois que tu as menti à quelqu\'un ici.',
  'Fais une bataille d\'eau / de regards avec {Joueur}.',
  'Laisse {Joueur} faire une story Insta depuis ton compte.',
  'Fais des bruits de la ferme jusqu\'à ce que quelqu\'un devine l\'animal.',
  'Dis à {Joueur} la chose que tu admires le plus chez lui.',
  'Fais un massage des mains à {Joueur} pendant 20 secondes.',
  'Organise un mini-débat avec {Joueur} sur un sujet absurde.',
  'Imite le style de marche de quelqu\'un ici.',
  'Fais une liste des meilleures qualités du groupe.',
  'Appelle un ami et demande-lui un conseil important sur un sujet bidon.',
  'Fais un selfie de groupe avec la langue sortie.',
  'Raconte ton plus beau souvenir avec quelqu\'un ici.',
  'Laisse {Joueur} choisir une musique et tu dois danser dessus.',
  'Fais deviner ta couleur préférée en la mimant.',
  'Dis à chaque personne ici un mot qui la représente.',
  'Porte un toast en l\'honneur de quelqu\'un ici.',
  'Fais un duel de danse folklorique avec {Joueur}.',
  'Laisse le groupe choisir une chanson et tu dois la chanter.',
  'Raconte une anecdote embarrassante impliquant {Joueur}.',
  'Fais une critique positive de chaque joueur.',
  'Mime une scène de film culte avec {Joueur}.',
  'Fais une promesse solennelle à quelqu\'un ici.',
  'Laisse {Joueur} te donner un ordre que tu dois exécuter.',
  'Fais un dessin représentant le groupe et montre-le.',
  'Organise un mini-quiz entre toi et {Joueur} sur la culture inutile.',
  'Fais un discours pour expliquer pourquoi {Joueur} est génial.',
  'Fais deviner ton film préféré à {Joueur} en le mimant.',
  'Échange un accessoire de mode avec quelqu\'un pour la soirée.',
  'Fais une photo avec l\'expression la plus drôle possible.',
  'Raconte la dernière fois que quelqu\'un ici t\'a déçu.',
  'Fais un jeu de mime avec {Joueur} sur le thème des animaux.',
  'Donne à {Joueur} le droit de poser une question indiscrète.',
  'Chante la chanson préférée de quelqu\'un ici.',

  // ───────── Croustillants (201-350) ─────────
  'Susurre un mot doux à l\'oreille de {Joueur}.',
  'Regarde {Joueur} dans les yeux pendant 10 secondes sans sourire.',
  'Chuchote ton plus gros secret à l\'oreille de {Joueur}.',
  'Fais une déclaration d\'amour passionnée à {Joueur}.',
  'Masse les épaules de {Joueur} pendant 15 secondes.',
  'Fais deviner un mot coquin à {Joueur} en le mimant.',
  'Fais un slow avec {Joueur} sur une musique imaginaire.',
  'Prends la main de {Joueur} et fais-lui un compliment les yeux dans les yeux.',
  'Embrasse la joue de {Joueur} lentement.',
  'Raconte une anecdote croustillante avec gestes.',
  'Fais un massage des mains à {Joueur} en le regardant dans les yeux.',
  'Susurre un compliment coquin à l\'oreille de {Joueur}.',
  'Regarde {Joueur} de bas en haut et devine sa pointure.',
  'Fais deviner à {Joueur} le mot que tu préfères dans la langue française.',
  'Chuchote à l\'oreille de quelqu\'un ce que tu ferais avec 1 million.',
  'Fais un clin d\'œil à {Joueur} et maintiens le regard.',
  'Fais un geste tendre à {Joueur} (effleurer la joue, etc.).',
  'Raconte un fantasme de voyage avec {Joueur}.',
  'Fais deviner ton plus gros secret en le mimant.',
  'Embrasse le creux de la main de {Joueur}.',
  'Chuchote une blague salace à l\'oreille de {Joueur}.',
  'Fais un compliment très personnel à {Joueur}.',
  'Regarde {Joueur} dans les yeux et dis-lui ce que tu remarques en premier le matin.',
  'Fais deviner ton plus gros défaut en le mimant.',
  'Susurre une promesse à l\'oreille de {Joueur}.',
  'Fais un geste que tu ne ferais normalement qu\'avec un partenaire.',
  'Raconte ton pire date à voix basse à {Joueur}.',
  'Embrasse le poignet de {Joueur}.',
  'Fais un slow main dans la main avec {Joueur}.',
  'Chuchote ton pire défaut à l\'oreille de {Joueur}.',
  'Fais un câlin par derrière à {Joueur}.',
  'Regarde {Joueur} dans les yeux et souris lentement.',
  'Fais deviner le plus beau compliment qu\'on t\'ait fait.',
  'Susurre un « je suis content d\'être là avec toi » à {Joueur}.',
  'Fais une caresse du bout des doigts sur la joue de {Joueur}.',
  'Fais un slow en gardant les yeux ouverts avec {Joueur}.',
  'Dis le mot le plus sensuel que tu connaisses à voix basse.',
  'Chuchote ce que tu aimerais faire demain matin à l\'oreille de {Joueur}.',
  'Fais un geste doux et inattendu à {Joueur}.',
  'Fais deviner ton plus grand plaisir simple en le mimant.',
  'Regarde {Joueur} dans les yeux et dis-lui un secret sur toi.',
  'Susurre un « tu as de beaux yeux » à {Joueur}.',
  'Fais un compliment sur l\'odeur de {Joueur}.',
  'Embrasse le haut de la main de {Joueur}.',
  'Fais un câlin prolongé de 15 secondes à {Joueur}.',
  'Prends le menton de {Joueur} et regarde-le doucement.',
  'Chuchote à l\'oreille de {Joueur} ce que tu ferais si vous étiez seuls.',
  'Fais deviner ton endroit préféré pour un baiser.',
  'Susurre une question coquine à l\'oreille de {Joueur}.',
  'Fais un compliment sur le regard de {Joueur}.',
  'Regarde {Joueur} sans rien dire pendant 10 secondes.',
  'Fais une déclaration sur ce que tu aimes chez les gens timides.',
  'Chuchote un mot dans une autre langue à l\'oreille de {Joueur}.',
  'Fais deviner ton parfum préféré en le mimant.',
  'Susurre une invitation à {Joueur} pour un café imaginaire.',
  'Fais un compliment sincère sur la personnalité de {Joueur}.',
  'Embrasse l\'épaule de {Joueur} (sur les vêtements).',
  'Chuchote ton plus beau souvenir à l\'oreille de {Joueur}.',
  'Fais deviner ton plus grand plaisir coupable.',
  'Regarde {Joueur} dans les yeux et dis-lui ce que tu aimes chez lui.',
  'Susurre un mot gentil à l\'oreille de chaque joueur.',
  'Fais un geste attentionné à {Joueur} (remettre une mèche).',
  'Embrasse le front de {Joueur}.',
  'Chuchote un compliment à propos du sourire de {Joueur}.',
  'Fais deviner la partie du corps que tu préfères.',
  'Susurre un mystère à l\'oreille de {Joueur}.',
  'Fais un slow en chuchotant une chanson à {Joueur}.',
  'Prends la main de {Joueur} et dessine un cœur dedans.',
  'Chuchote ton plus grand rêve à l\'oreille de {Joueur}.',
  'Fais deviner ce qui te rend le plus heureux.',
  'Susurre un « tu me plais » à l\'oreille de {Joueur}.',
  'Fais un massage du cou à {Joueur} pendant 10 secondes.',
  'Embrasse la tempe de {Joueur}.',
  'Chuchote une confidence à l\'oreille de {Joueur}.',
  'Fais deviner ta couleur préférée de lingerie.',
  'Regarde {Joueur} intensément et dis-lui ce que tu vois.',
  'Susurre une douceur à l\'oreille de {Joueur}.',
  'Fais une caresse dans les cheveux de {Joueur}.',
  'Chuchote ce que tu ferais pour rendre {Joueur} heureux.',
  'Fais deviner ton pire défaut en amour.',
  'Susurre un compliment sur la voix de {Joueur}.',
  'Fais un câlin à {Joueur} et tapote-lui le dos doucement.',
  'Embrasse le coin des lèvres de {Joueur} (presque).',
  'Chuchote ton plus grand secret à quelqu\'un d\'autre que {Joueur}.',
  'Fais deviner ton plat aphrodisiaque préféré.',
  'Susurre une vérité que tu n\'as jamais dite à personne.',
  'Fais un compliment sur le rire de {Joueur}.',
  'Regarde {Joueur} dans les yeux et souris mystérieusement.',
  'Chuchote une question que tu n\'oserais jamais poser à voix haute.',
  'Fais deviner ta plus grande peur en la mimant.',
  'Susurre un remerciement spécial à {Joueur}.',
  'Fais une confidence sur ton plus grand regret.',
  'Embrasse la nuque de {Joueur} (sur les cheveux).',
  'Chuchote un « j\'aimerais te connaître plus » à {Joueur}.',
  'Fais deviner le plus beau compliment que tu aimerais recevoir.',
  'Susurre une évidence que tu trouves belle chez {Joueur}.',
  'Fais un geste qui veut dire « tu comptes pour moi ».',
  'Chuchote un souvenir de vous deux à {Joueur} (si vous vous connaissez).',
  'Fais deviner la personne ici que tu trouves la plus mystérieuse.',
  'Susurre quelque chose que tu n\'as jamais dit à personne ici.',
  'Fais un slow avec {Joueur} en comptant tout bas.',
  'Chuchote un mot qui rime avec ton prénom à l\'oreille de {Joueur}.',

  // ───────── Hot / Osées (351-450) ─────────
  'Mime une scène de séduction avec {Joueur} devant tout le monde.',
  'Regarde {Joueur} de bas en haut et dis-lui ce qui te plaît chez lui.',
  'Danse langoureusement avec un objet imaginaire 15 secondes.',
  'Fais ton regard le plus séducteur à {Joueur} sans cligner.',
  'Fais une proposition indécente à {Joueur} sur ton théâtral.',
  'Décoiffe-toi façon clip de musique.',
  'Fais un strip-tease inversé (remets un vêtement lentement).',
  'Chuchote une phrase hot à l\'oreille de {Joueur}.',
  'Fais un slow très collé avec {Joueur} sur une musique imaginaire.',
  'Mime une scène de film érotique avec {Joueur}.',
  'Fais deviner un geste coquin à {Joueur} en le mimant.',
  'Fais un compliment très sensuel à {Joueur} en le regardant dans les yeux.',
  'Fais une danse sensuelle sur 15 secondes.',
  'Prends la main de {Joueur} et embrasse ses doigts un par un.',
  'Regarde {Joueur} comme si tu voulais l\'embrasser pendant 10 secondes.',
  'Fais deviner ton endroit préféré pour un rendez-vous hot.',
  'Susurre un « j\'ai envie de toi » théâtral à {Joueur}.',
  'Fais un massage sensuel des épaules à {Joueur}.',
  'Embrasse le cou de {Joueur} (sur les vêtements).',
  'Fais une déclaration de désir à {Joueur} façon film.',
  'Danse comme si tu voulais attirer l\'attention de quelqu\'un.',
  'Fais deviner ce qui te rend le plus excité dans la vie.',
  'Regarde {Joueur} de façon appuyée en mordant ta lèvre inférieure.',
  'Chuchote un compliment sur le corps de {Joueur}.',
  'Fais un geste lent et sensuel avec ta main devant {Joueur}.',
  'Mime une scène de douche avec {Joueur} (PG-13).',
  'Susurre ce que tu ferais si vous étiez sur une île déserte.',
  'Fais un slow en gardant les yeux fermés avec {Joueur}.',
  'Embrasse l\'épaule découverte de {Joueur}.',
  'Fais deviner le mot le plus hot de la langue française.',
  'Chuchote un compliment sur les lèvres de {Joueur}.',
  'Fais un geste suggestif avec un objet du quotidien.',
  'Regarde {Joueur} intensément sans parler pendant 15 secondes.',
  'Fais une caresse du dos à {Joueur} (sur les vêtements).',
  'Susurre une question très personnelle à {Joueur}.',
  'Fais deviner ta position préférée en la mimant (soft).',
  'Danse avec {Joueur} comme si vous étiez dans un film de James Bond.',
  'Chuchote à l\'oreille de {Joueur} : « tu sens bon ».',
  'Fais un massage du cou sensuel à {Joueur}.',
  'Mime une scène de bougie et de massage.',
  'Regarde {Joueur} de bas en haut avec un sourire en coin.',
  'Fais deviner quel est le mot le plus sexy pour toi.',
  'Susurre une invitation à un dîner aux chandelles à {Joueur}.',
  'Fais un slow très proche sans musique.',
  'Embrasse la paume de la main de {Joueur}.',
  'Chuchote une question à {Joueur} : « qu\'est-ce qui te fait craquer ? »',
  'Fais une caresse du genou à {Joueur} (si position possible).',
  'Mime une scène de boudoir avec un objet.',
  'Susurre ton plus gros fantasme à voix très basse.',
  'Fais deviner le type de baiser que tu préfères.',
  'Regarde {Joueur} dans les yeux en te léchant les lèvres.',
  'Fais une danse lente suggestive avec un seul accessoire.',
  'Chuchote à l\'oreille de {Joueur} : « si on était seuls... ».',
  'Fais un geste sensuel avec un glaçon imaginaire.',
  'Mime une scène où tu mets de la musique d\'ambiance.',
  'Susurre un compliment sur le style de {Joueur}.',
  'Fais deviner ce qui te fait le plus craquer chez {Joueur}.',
  'Danse langoureusement avec ton propre reflet (miroir imaginaire).',
  'Regarde {Joueur} par-dessus ton épaule.',
  'Chuchote une vérité que tu n\'as jamais dite à voix haute.',
  'Fais un strip symbolique (enlève une bague, un bracelet, lentement).',
  'Susurre une déclaration de passion à {Joueur}.',
  'Fais deviner ta boisson préférée pour un date.',
  'Mime une scène de premier rendez-vous réussi.',
  'Embrasse le bout des doigts de {Joueur}.',
  'Chuchote à l\'oreille de {Joueur} : « tu me troubles ».',
  'Fais un geste de séduction avec une mèche de cheveux.',
  'Susurre un poème d\'amour improvisé à {Joueur}.',
  'Fais deviner ton parfum de séduction préféré.',
  'Regarde {Joueur} les yeux mi-clos pendant 10 secondes.',
  'Danse sensuellement avec un coussin.',
  'Chuchote un mot tabou à l\'oreille de {Joueur}.',
  'Fais un câlin par derrière à {Joueur} en chuchotant un compliment.',
  'Susurre ce qui te plaît physiquement chez {Joueur}.',
  'Mime une scène de slow dans une soirée enfumée.',
  'Embrasse l\'oreille de {Joueur} (à travers les cheveux).',
  'Chuchote une promesse de soirée à {Joueur}.',
  'Fais deviner le son qui te rend le plus excité.',
  'Regarde {Joueur} en penchant la tête doucement.',
  'Susurre un joli mensonge à l\'oreille de {Joueur}.',
  'Fais une danse suggestive en utilisant une chaise.',
  'Chuchote à l\'oreille de {Joueur} ce que tu remarques en premier chez lui.',
  'Mime une scène de baiser dans un film.',
  'Embrasse le coin de la bouche de {Joueur}.',
  'Susurre un compliment sur les yeux de {Joueur}.',
  'Fais deviner ta couleur de lingerie préférée.',
  'Danse avec {Joueur} en gardant une distance qui donne envie.',
  'Regarde {Joueur} droit dans les yeux sans rien dire.',
  'Chuchote une confidence sur ton désir à {Joueur}.',
  'Fais un geste de possession douce (main sur l\'épaule).',
  'Susurre ce que tu ferais si c\'était votre dernier jour.',
  'Mime une scène de séduction dans un ascenseur.',
  'Embrasse la joue de {Joueur} près des lèvres.',
  'Chuchote une question indiscrète mais pas vulgaire.',
  'Fais deviner la partie du corps que tu aimes embrasser.',

  // ───────── Inconfortables / Extrêmes (451-500) ─────────
  'Mange une cuillère de moutarde ou de sauce piquante.',
  'Laisse quelqu\'un te coiffer comme il veut et garde la coupe 30 min.',
  'Mets un glaçon dans ton pantalon jusqu\'à ce qu\'il fonde.',
  'Mange un morceau d\'ail cru.',
  'Laisse quelqu\'un t\'épiler un petit bout de jambe/bras.',
  'Casse un œuf sur ta tête.',
  'Fais 50 squats en moins de 2 minutes.',
  'Tiens en équilibre sur une jambe yeux fermés 1 minute.',
  'Sniffe le dessous de bras de {Joueur}.',
  'Marche à 4 pattes jusqu\'à la cuisine et reviens.',
  'Appelle ton ex et dis « Tu me manques ».',
  'Envoie un message « Je suis enceinte / Je vais être papa » à tes parents.',
  'Hurle « J\'ai la diarrhée » par la fenêtre.',
  'Fais un live Instagram en chantant Disney.',
  'Envoie un sexto à la 3ème personne de tes contacts.',
  'Montre tes derniers DM Instagram au groupe.',
  'Demande en mariage {Joueur} avec une bague imaginaire.',
  'Laisse quelqu\'un envoyer un snap à tous tes contacts.',
  'Fais 10 pompes en grognant comme dans un film X.',
  'Laisse le groupe envoyer un DM à qui ils veulent depuis ton Insta.',
  'Appelle ta mère et dis que tu vas te marier demain.',
  'Fais 20 pompes en chantant du Céline Dion.',
  'Simule un orgasme bruyant pendant 15 secondes.',
  'Lèche le pied de {Joueur} ou le gros orteil.',
  'Laisse quelqu\'un lire ta dernière note téléphone à voix haute.',
  'Appelle un resto et essaie de commander un McDo.',
  'Fais une déclaration d\'amour enflammée à une plante.',
  'Sent les aisselles de {Joueur} et décris l\'odeur.',
  'Montre ton temps d\'écran à tout le monde.',
  'Like les 5 premières photos Insta de ton ex.',
  'Montre la photo la plus récente de ta galerie sans exception.',
  'Déverrouille ton téléphone et donne-le au groupe 2 minutes.',
  'Montre tes 3 dernières recherches Insta.',
  'Fais croire à quelqu\'un par SMS que tu as gagné au loto.',
  'Envoie « J\'ai caché le corps » à un membre de ta famille.',
  'Envoie « Je suis adopté ? » à tes parents.',
  'Laisse le groupe répondre au prochain message que tu reçois.',
  'Poste un statut « Je me marie demain » sans répondre 30 min.',
  'Fais 5 minutes de planche.',
  'Mange un oignon cru comme une pomme.',
  'Laisse quelqu\'un dessiner sur ton visage au marqueur.',
  'Fais un discours de 2 minutes sur un sujet que tu ne maîtrises pas.',
  'Récite la liste des départements français dans le désordre.',
  'Essaie de faire le grand écart (ou au maximum de tes capacités).',
  'Fais 10 burpees.',
  'Chante l\'hymne national à l\'envers.',
  'Garde la bouche ouverte 30 secondes sans fermer.',
  'Fais une imitation parfaite de la personne que tu détestes le plus.',
  'Parle sans arrêter de cligner des yeux pendant 2 minutes.',
  'Fais le bruit d\'un pet avec tes aisselles.',
  'Raconte l\'histoire de ta vie en 30 secondes chrono.',
  'Fais un câlin à un arbre dehors et dis-lui un secret.',
  'Essaie de faire un wheeling sur une chaise de bureau.',
  'Laisse {Joueur} lancer un défi à quelqu\'un d\'autre via ton téléphone.',
  'Fais deviner un mot à {Joueur} en le dessinant sur son dos avec ton doigt.',
  'Fais une imitation de la météo en version dramatique.',
  'Prends un objet et fais-en la pub comme un télé-achat.',
  'Chante la chanson du générique d\'un dessin animé de ton enfance.',
  'Raconte un conte pour enfants version horreur.',
  'Fais une interview de {Joueur} comme si c\'était une star.',
  'Fais le robot pendant 30 secondes.',
  'Mime une scène de film d\'action au ralenti.',
  'Parle en chuchotant jusqu\'à ton prochain tour.',
  'Fais une démonstration de self-défense imaginaire.',
  'Imite un chanteur d\'opéra en plein concert.',
  'Fais deviner une célébrité à {Joueur} en la mimant.',
  'Fais une crise de folie douce (gestes lents et cheveux en bataille).',
  'Danse comme un personnage de Fortnite.',
  'Fais un bruit de bateau qui coule.',
  'Mime un boxeur qui gagne un combat.',
  'Imite un commentateur sportif qui décrit ta vie.',
  'Fais semblant de jouer à la pétanque devant tout le monde.',
  'Fais une démonstration de yoga absurde (5 poses en 30 sec).',
  'Imite une personne qui fait du patin à glace pour la première fois.',
  'Fais un discours de remerciement aux toilettes pour leur service.',
  'Fais un playback d\'une chanson choisie par {Joueur}.',
  'Mime un pope qui bénit la tablée.',
  'Imite un fantôme qui hante la pièce.',
  'Fais le bruit d\'un train à vapeur.',
  'Danse le rock\'n\'roll tout seul.',
  'Mime un lanceur de javelot.',
  'Imite un crabe qui fait du moonwalk.',
  'Fais la démonstration d\'un appareil de fitness imaginaire.',
  'Parle avec la voix de Batman jusqu\'à ton prochain tour.',
  'Fais une imitation de la reine d\'Angleterre saluant la foule.',
  'Mime un magicien qui rate son tour.',
  'Imite un pigeon qui se pavane.',
  'Fais une proclamation royale debout sur ta chaise.',
  'Fais des bisous à {Joueur} sur chaque joue.',
  'Fais deviner le nom de ton premier amour en le mimant.',
];

class LeTozGame {
  constructor(redis) {
    this.redis = redis;
  }

  async createGame(hostId, hostName, hostAvatar, variantRules) {
    let state, key;
    for (let attempt = 0; attempt < 10; attempt++) {
      state = {
        id: generateCode(),
        gameType: 'le-toz',
        status: GAME_STATUS.WAITING,
        players: [{ id: hostId, name: hostName, avatar: hostAvatar || '🃏', penaltyPoints: 0 }],
        turnOrder: [hostId],
        currentTurnIndex: 0,
        currentCard: null,
        currentPlayerId: null,
        hostId,
        logs: [],
        createdAt: Date.now(),
      };
      key = redisKey(ROOM_PREFIX, state.id);
      const exists = await this.redis.exists(key);
      if (!exists) break;
    }
    await this.redis.set(key, JSON.stringify(state), 'EX', GAME_TTL);
    return state;
  }

  async getGame(gameId) {
    const key = redisKey(ROOM_PREFIX, gameId);
    const raw = await this.redis.get(key);
    return raw ? JSON.parse(raw) : null;
  }

  async saveGame(state) {
    const key = redisKey(ROOM_PREFIX, state.id);
    await this.redis.set(key, JSON.stringify(state), 'EX', GAME_TTL);
  }

  async joinGame(gameId, playerId, playerName, playerAvatar) {
    const state = await this.getGame(gameId);
    if (!state) throw new Error('Partie introuvable');
    if (state.status !== GAME_STATUS.WAITING) throw new Error('Partie déjà commencée');
    if (state.players.find((p) => p.id === playerId)) return state;
    if (state.players.length >= 12) throw new Error('Partie complète (max 12 joueurs)');
    state.players.push({ id: playerId, name: playerName, avatar: playerAvatar || '🃏', penaltyPoints: 0 });
    state.turnOrder.push(playerId);
    await this.saveGame(state);
    return state;
  }

  async leaveGame(gameId, playerId) {
    const state = await this.getGame(gameId);
    if (!state) throw new Error('Partie introuvable');
    state.players = state.players.filter((p) => p.id !== playerId);
    state.turnOrder = state.turnOrder.filter((id) => id !== playerId);
    if (state.players.length === 0) {
      await this.redis.del(redisKey(ROOM_PREFIX, gameId));
      return null;
    }
    if (state.hostId === playerId) state.hostId = state.players[0]?.id || null;
    await this.saveGame(state);
    return state;
  }

  async startGame(gameId) {
    const state = await this.getGame(gameId);
    if (!state) throw new Error('Partie introuvable');
    if (state.players.length < 2) throw new Error('Minimum 2 joueurs requis');
    state.status = GAME_STATUS.PLAYING;
    state.currentCard = null;
    state.currentPlayerId = null;
    state.currentTurnIndex = 0;
    state.logs.push({ type: 'gameStarted' });
    await this.saveGame(state);
    return state;
  }

  async drawCard(gameId) {
    const state = await this.getGame(gameId);
    if (!state) throw new Error('Partie introuvable');
    if (state.status !== GAME_STATUS.PLAYING) throw new Error('Partie pas en cours');

    const activePlayers = state.players.filter((p) => state.turnOrder.includes(p.id));
    if (activePlayers.length === 0) throw new Error('Aucun joueur actif');

    const randomIndex = Math.floor(Math.random() * activePlayers.length);
    const player = activePlayers[randomIndex];

    const isVerite = Math.random() < 0.5;
    const deck = isVerite ? VERITE_CARDS : ACTION_CARDS;
    let text = deck[Math.floor(Math.random() * deck.length)];

    if (text.includes('{Joueur}')) {
      const others = activePlayers.filter((p) => p.id !== player.id);
      if (others.length > 0) {
        const target = others[Math.floor(Math.random() * others.length)];
        text = text.replace(/\{Joueur\}/g, target.name);
      } else {
        text = text.replace(/\{Joueur\}/g, 'toi-même');
      }
    }

    state.currentPlayerId = player.id;
    state.currentCard = { type: isVerite ? 'verite' : 'action', text };
    state.logs.push({ type: 'cardDrawn', playerId: player.id, cardType: state.currentCard.type });

    state.currentTurnIndex = (state.currentTurnIndex + 1) % state.turnOrder.length;
    await this.saveGame(state);
    return state;
  }

  async resetGame(gameId) {
    const state = await this.getGame(gameId);
    if (!state) throw new Error('Partie introuvable');
    state.status = GAME_STATUS.WAITING;
    state.currentCard = null;
    state.currentPlayerId = null;
    state.currentTurnIndex = 0;
    state.logs = [];
    state.players.forEach((p) => { p.penaltyPoints = 0; });
    await this.saveGame(state);
    return state;
  }
}

module.exports = { LeTozGame, GAME_STATUS, ROOM_PREFIX };
